<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Physical AI</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../16_release/16_release.html" rel="prev">
<link href="../shared/assets/images/icons/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-da245a98686d0485553d61919e8b3534.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-da245a98686d0485553d61919e8b3534.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-da245a98686d0485553d61919e8b3534.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0d82195d1e503b27f157dcc767841759.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-3633dbbe5d853a520d2eb141409a8117.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-0d82195d1e503b27f157dcc767841759.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/foldbox/foldbox.css" rel="stylesheet">
<script src="../site_libs/quarto-contrib/pseudocode-2.4.1/pseudocode.min.js"></script>
<link href="../site_libs/quarto-contrib/pseudocode-2.4.1/pseudocode.min.css" rel="stylesheet">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "/"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Shared head includes — MLSysBook ecosystem -->

<!--
  theme-persist (inline, sync) — applies stored color-scheme before first paint.
  Inlined deliberately: runs before any other <script>, no extra round-trip,
  and avoids per-subsite asset path differences. Canonical source:
  shared/scripts/theme-persist.js (kept identical for documentation/testability).
  If you change one, mirror the change to the other.
-->
<script>
(function () {
  'use strict';
  var STORAGE_KEY = 'quarto-color-scheme';
  // Quarto's toggle writes 'alternate'/'default' (alternate = dark, the
  // layered sheet); sibling non-Quarto sites write 'dark'/'light'. Both
  // hit the same key, so we accept either. Quarto's own startup still
  // checks `=== 'alternate'`, so we mirror onto <html> rather than rewrite.
  function normalize(v) {
    if (v === 'dark' || v === 'alternate') return 'dark';
    if (v === 'light' || v === 'default') return 'light';
    return null;
  }
  function preferredScheme() {
    try {
      var n = normalize(window.localStorage.getItem(STORAGE_KEY));
      if (n) return n;
    } catch (e) {}
    if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
      return 'dark';
    }
    return 'light';
  }
  function apply(scheme) {
    var html = document.documentElement;
    if (!html) return;
    html.setAttribute('data-bs-theme', scheme);
    html.setAttribute('data-quarto-color-scheme', scheme);
    html.style.colorScheme = scheme;
    // Bridge to legacy `.quarto-dark` body class — about.css,
    // community.css, and newsletter.css key their dark-mode CSS
    // variables off `.quarto-dark { ... }`. Quarto's own toggle adds
    // that class on click, but the OS-pref / first-paint path never
    // does. Mirror the scheme onto body so those CSS variables fire
    // on every dark path, not just toggle clicks. body may not exist
    // yet on the first call (this script runs in <head>); a
    // MutationObserver below catches it as soon as it parses.
    var body = document.body;
    if (body) body.classList.toggle('quarto-dark', scheme === 'dark');
  }
  apply(preferredScheme());
  // Catch the FOUC window between <head> apply() and DOMContentLoaded:
  // <body> may not exist yet at first apply(), but as soon as the
  // parser appends it we want the legacy class bridge in place so any
  // CSS keyed on `.quarto-dark` paints correctly on first render.
  if (!document.body) {
    var earlyObserver = new MutationObserver(function () {
      if (document.body) {
        apply(preferredScheme());
        earlyObserver.disconnect();
      }
    });
    earlyObserver.observe(document.documentElement, { childList: true });
  }
  // Quarto's toggle updates localStorage but not <html>, so wrap it to
  // mirror the new value onto data-bs-theme; otherwise clicking the toggle
  // leaves CSS keyed off [data-bs-theme="dark"] rendering against the wrong
  // stylesheet until the next reload.
  function syncFromStorage() {
    try {
      var n = normalize(window.localStorage.getItem(STORAGE_KEY));
      if (n) apply(n);
    } catch (e) {}
  }
  function wrapToggle() {
    var orig = window.quartoToggleColorScheme;
    if (typeof orig !== 'function' || orig.__mlsbWrapped) return;
    var wrapped = function () { var r = orig.apply(this, arguments); syncFromStorage(); return r; };
    wrapped.__mlsbWrapped = true;
    window.quartoToggleColorScheme = wrapped;
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { wrapToggle(); syncFromStorage(); });
  } else {
    wrapToggle(); syncFromStorage();
  }
  // Defend the legacy `.quarto-dark` body class against Quarto's own
  // `toggleBodyColor(mode)`, which runs *after* this script and re-asserts
  // the body class based on `mode` — and `mode` defaults to 'light' when
  // there's no stored quarto-color-scheme value, even when the OS / first
  // paint already resolved to dark via `data-bs-theme`. Without this
  // observer, on every fresh visit Quarto would clobber our bridge and
  // restore `.quarto-light`, leaving `.quarto-dark`-keyed CSS variables
  // (about/community/newsletter pages) at their light-mode defaults
  // against the dark `data-bs-theme="dark"` background.
  function bridgeBody() {
    var body = document.body;
    if (!body) return;
    var wantDark = document.documentElement.getAttribute('data-bs-theme') === 'dark';
    if (wantDark && !body.classList.contains('quarto-dark')) {
      body.classList.add('quarto-dark');
      body.classList.remove('quarto-light');
    } else if (!wantDark && body.classList.contains('quarto-dark')) {
      body.classList.remove('quarto-dark');
      body.classList.add('quarto-light');
    }
  }
  function watchBody() {
    if (!document.body) return;
    bridgeBody();
    var bodyObs = new MutationObserver(bridgeBody);
    bodyObs.observe(document.body, { attributes: true, attributeFilter: ['class'] });
    var htmlObs = new MutationObserver(bridgeBody);
    htmlObs.observe(document.documentElement, { attributes: true, attributeFilter: ['data-bs-theme'] });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', watchBody);
  } else {
    watchBody();
  }
  window.addEventListener('storage', function (ev) {
    if (ev.key !== STORAGE_KEY) return;
    var n = normalize(ev.newValue);
    if (n) apply(n);
  });
  if (window.matchMedia) {
    try {
      window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', function (ev) {
        try { if (window.localStorage.getItem(STORAGE_KEY)) return; } catch (e) {}
        apply(ev.matches ? 'dark' : 'light');
      });
    } catch (e) {}
  }
})();
</script>

<!--
  Build-stamp styling. Tiny, neutral, dark-mode aware. The actual stamp text
  is injected by shared/scripts/inject-build-stamp.sh into footer markup
  containing the literal MLSB_BUILD_STAMP HTML-comment token (see that
  script for the exact pattern — we cannot write it here because HTML
  comments cannot nest and the inner closer would terminate this block).
-->
<style>
.mlsb-build-stamp {
  display: inline-block;
  margin-top: 0.25rem;
  font-size: 0.75rem;
  opacity: 0.6;
  font-variant-numeric: tabular-nums;
}
[data-bs-theme="dark"] .mlsb-build-stamp { opacity: 0.5; }
</style>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&amp;family=JetBrains+Mono:wght@400;500&amp;display=swap" rel="stylesheet">
<link rel="icon" href="../../vol1/assets/images/icons/favicon.png" type="image/png">
<meta name="author" content="Vijay Janapa Reddi">

<!-- Schema.org JSON-LD structured data for Google Knowledge Graph & Rich Snippets -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": "https://mlsysbook.ai/#website",
      "url": "https://mlsysbook.ai/",
      "name": "Machine Learning Systems",
      "description": "The AI Engineering Textbook Series: Foundations, Scaling, Agentic AI, and Physical AI.",
      "publisher": {
        "@type": "Organization",
        "name": "Harvard Edge Computing Lab",
        "url": "https://edge.seas.harvard.edu"
      }
    },
    {
      "@type": "BookSeries",
      "@id": "https://mlsysbook.ai/#bookseries",
      "name": "Machine Learning Systems: Principles and Practices of Engineering Artificially Intelligent Systems",
      "alternateName": ["MLSysBook", "Machine Learning Systems", "AI Engineering Textbook"],
      "url": "https://mlsysbook.ai/",
      "inLanguage": "en-US",
      "author": {
        "@type": "Person",
        "name": "Vijay Janapa Reddi",
        "jobTitle": "Gordon McKay Professor of Electrical Engineering and Computer Science",
        "worksFor": {
          "@type": "EducationalOrganization",
          "name": "Harvard University",
          "sameAs": "https://www.harvard.edu"
        },
        "sameAs": [
          "https://profvjreddi.github.io/homepage/"
        ]
      },
      "publisher": {
        "@type": "Organization",
        "name": "MIT Press",
        "url": "https://mitpress.mit.edu"
      },
      "hasPart": [
        {
          "@type": "Book",
          "name": "Volume I: Introduction to Machine Learning Systems",
          "url": "../../vol1/",
          "bookFormat": "https://schema.org/EBook",
          "about": "Foundations, Lifecycle, Data Engineering, Training, Inference, Benchmarking, and Responsible AI"
        },
        {
          "@type": "Book",
          "name": "Volume II: Scaling Machine Learning Systems",
          "url": "../../vol2/",
          "bookFormat": "https://schema.org/EBook",
          "about": "Distributed Training, Accelerator Architecture, Parallelism, Memory Systems, and Serving"
        },
        {
          "@type": "Book",
          "name": "Volume III: Agentic Machine Learning Systems",
          "url": "../../vol3/",
          "bookFormat": "https://schema.org/EBook",
          "about": "Autonomous Agents, Deliberation, Working Sets, Virtual Memory, RAG, RLVR, and Multi-Agent Systems"
        },
        {
          "@type": "Book",
          "name": "Volume IV: Physical AI Systems",
          "url": "../",
          "bookFormat": "https://schema.org/EBook",
          "about": "Physical AI, Embodied AI, Closed-Loop Dynamics, Actuation, Control Barrier Functions, and Robotics"
        }
      ]
    },
    {
      "@type": "Course",
      "@id": "https://mlsysbook.ai/#course",
      "name": "CS249r: Machine Learning Systems",
      "description": "Harvard University course on principles and practices of engineering artificially intelligent systems.",
      "provider": {
        "@type": "EducationalOrganization",
        "name": "Harvard University",
        "sameAs": "https://www.harvard.edu"
      }
    }
  ]
}
</script>

<!--
  navbar-theme-toggle-relocate — moves the Quarto theme toggle into the
  navbar's right-side .navbar-nav group at page load, so it collapses into
  the hamburger menu alongside Subscribe/Star/Support/GitHub at narrow widths
  instead of being stranded in the middle by Quarto's mx-auto brand layout.

  Why JS: Quarto auto-injects the toggle into .quarto-navbar-tools (outside
  .navbar-collapse). CSS can't move DOM nodes between containers, and CSS
  positioning hacks (absolute/right: 50px) fight Bootstrap's responsive
  layout below 992px. Moving the node once at startup is the standard
  approach used across Quarto-based sites with the same problem.
-->
<script>
(function () {
  'use strict';
  function relocateThemeToggle() {
    var tools = document.querySelector('.quarto-navbar-tools');
    if (!tools) return;
    var toggle = tools.querySelector('.quarto-color-scheme-toggle');
    if (!toggle) return;
    var navRight = document.querySelector(
      '.navbar .navbar-collapse .navbar-nav.ms-auto'
    ) || document.querySelector(
      '.navbar .navbar-collapse .navbar-nav:last-of-type'
    );
    if (!navRight) return;
    var li = document.createElement('li');
    li.className = 'nav-item navbar-theme-toggle-item';
    toggle.classList.add('nav-link');
    li.appendChild(toggle);
    navRight.appendChild(li);
    tools.style.display = 'none';
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', relocateThemeToggle);
  } else {
    relocateThemeToggle();
  }
})();
</script>

<!--
  navbar-brand-href-fix — force the navbar brand link to the ecosystem root
  (https://mlsysbook.ai/) on every subsite.

  Quarto sets each subsite's `site-url` to `https://mlsysbook.ai/<subsite>/`
  and then relativizes any navbar.href value that lives inside the
  site-url's domain. The shared `href: https://mlsysbook.ai/` in
  navbar-common.yml therefore gets emitted as `./index.html`, which on
  vol1/vol2/tinytorch/etc. resolves to *that subsite's* root rather than
  the ecosystem landing page. Override the brand link href in JS after
  Quarto's render: this is a one-line user-experience fix that does not
  fight Quarto's URL machinery.
-->
<script>
(function () {
  'use strict';
  function fixBrandHref() {
    var brand = document.querySelectorAll(
      '.navbar .navbar-brand, .navbar .navbar-brand-logo'
    );
    for (var i = 0; i < brand.length; i++) {
      brand[i].setAttribute('href', 'https://mlsysbook.ai/');
    }
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', fixBrandHref);
  } else {
    fixBrandHref();
  }
})();
</script>
<link rel="manifest" href="../site.webmanifest">
<link rel="apple-touch-icon" href="../shared/assets/images/icons/favicon.png">
<meta name="theme-color" content="#065F46">
<script src="../shared/assets/scripts/sidebar-auto-collapse.js" defer=""></script>
<script src="../shared/assets/scripts/version-link.js" defer=""></script>
<script src="../shared/assets/scripts/subscribe-modal.js" defer=""></script>
<style>
.callout-definition {
  --color1: #F2F7FA;
  --color2: #4F7396;
  --border-color: #4F7396;
  --background-color: rgba(79, 115, 150, 0.04);
  --title-background-color: rgba(79, 115, 150, 0.04);
  --dark-background-color: rgba(79, 115, 150, 0.12);
  --dark-title-background-color: rgba(79, 115, 150, 0.12);
}
.callout-chapter-connection {
  --color1: #F1F5F9;
  --color2: #64748B;
  --border-color: #64748B;
  --background-color: rgba(100, 116, 139, 0.04);
  --title-background-color: rgba(100, 116, 139, 0.04);
  --dark-background-color: rgba(100, 116, 139, 0.12);
  --dark-title-background-color: rgba(100, 116, 139, 0.12);
}
.callout-case-study {
  --color1: #FEF2F2;
  --color2: #C53030;
  --border-color: #C53030;
  --background-color: rgba(197, 48, 48, 0.04);
  --title-background-color: rgba(197, 48, 48, 0.04);
  --dark-background-color: rgba(197, 48, 48, 0.12);
  --dark-title-background-color: rgba(197, 48, 48, 0.12);
}
.callout-principle {
  --color1: #F3F2FA;
  --color2: #3D3B8E;
  --border-color: #3D3B8E;
  --background-color: rgba(61, 59, 142, 0.04);
  --title-background-color: rgba(61, 59, 142, 0.04);
  --dark-background-color: rgba(61, 59, 142, 0.12);
  --dark-title-background-color: rgba(61, 59, 142, 0.12);
}
.callout-theorem {
  --color1: #F5F0FA;
  --color2: #6B46C1;
  --border-color: #6B46C1;
  --background-color: rgba(107, 70, 193, 0.04);
  --title-background-color: rgba(107, 70, 193, 0.04);
  --dark-background-color: rgba(107, 70, 193, 0.12);
  --dark-title-background-color: rgba(107, 70, 193, 0.12);
}
.callout-lighthouse {
  --color1: #FDF8E6;
  --color2: #B8860B;
  --border-color: #B8860B;
  --background-color: rgba(184, 134, 11, 0.04);
  --title-background-color: rgba(184, 134, 11, 0.04);
  --dark-background-color: rgba(184, 134, 11, 0.12);
  --dark-title-background-color: rgba(184, 134, 11, 0.12);
}
.callout-research-questions {
  --color1: #F0F0F8;
  --color2: #5B4B8A;
  --border-color: #5B4B8A;
  --background-color: rgba(91, 75, 138, 0.04);
  --title-background-color: rgba(91, 75, 138, 0.04);
  --dark-background-color: rgba(91, 75, 138, 0.12);
  --dark-title-background-color: rgba(91, 75, 138, 0.12);
}
.callout-quiz-question {
  --color1: #F0F0F8;
  --color2: #5B4B8A;
  --border-color: #5B4B8A;
  --background-color: rgba(91, 75, 138, 0.04);
  --title-background-color: rgba(91, 75, 138, 0.04);
  --dark-background-color: rgba(91, 75, 138, 0.12);
  --dark-title-background-color: rgba(91, 75, 138, 0.12);
}
.callout-resource-exercises {
  --color1: #E0F2F1;
  --color2: #20B2AA;
  --border-color: #20B2AA;
  --background-color: rgba(32, 178, 170, 0.04);
  --title-background-color: rgba(32, 178, 170, 0.04);
  --dark-background-color: rgba(32, 178, 170, 0.12);
  --dark-title-background-color: rgba(32, 178, 170, 0.12);
}
.callout-perspective {
  --color1: #F7F8FA;
  --color2: #4A5568;
  --border-color: #4A5568;
  --background-color: rgba(74, 85, 104, 0.04);
  --title-background-color: rgba(74, 85, 104, 0.04);
  --dark-background-color: rgba(74, 85, 104, 0.12);
  --dark-title-background-color: rgba(74, 85, 104, 0.12);
}
.callout-resource-videos {
  --color1: #E0F2F1;
  --color2: #20B2AA;
  --border-color: #20B2AA;
  --background-color: rgba(32, 178, 170, 0.04);
  --title-background-color: rgba(32, 178, 170, 0.04);
  --dark-background-color: rgba(32, 178, 170, 0.12);
  --dark-title-background-color: rgba(32, 178, 170, 0.12);
}
.callout-checkpoint {
  --color1: #F7FEE7;
  --color2: #4D7C0F;
  --border-color: #4D7C0F;
  --background-color: rgba(77, 124, 15, 0.04);
  --title-background-color: rgba(77, 124, 15, 0.04);
  --dark-background-color: rgba(77, 124, 15, 0.12);
  --dark-title-background-color: rgba(77, 124, 15, 0.12);
}
.callout-takeaways {
  --color1: #FCF4F8;
  --color2: #9D3C72;
  --border-color: #9D3C72;
  --background-color: rgba(157, 60, 114, 0.04);
  --title-background-color: rgba(157, 60, 114, 0.04);
  --dark-background-color: rgba(157, 60, 114, 0.12);
  --dark-title-background-color: rgba(157, 60, 114, 0.12);
}
.callout-resource-slides {
  --color1: #E0F2F1;
  --color2: #20B2AA;
  --border-color: #20B2AA;
  --background-color: rgba(32, 178, 170, 0.04);
  --title-background-color: rgba(32, 178, 170, 0.04);
  --dark-background-color: rgba(32, 178, 170, 0.12);
  --dark-title-background-color: rgba(32, 178, 170, 0.12);
}
.callout-code {
  --color1: #F2F4F8;
  --color2: #3C4858;
  --border-color: #3C4858;
  --background-color: rgba(60, 72, 88, 0.04);
  --title-background-color: rgba(60, 72, 88, 0.04);
  --dark-background-color: rgba(60, 72, 88, 0.12);
  --dark-title-background-color: rgba(60, 72, 88, 0.12);
}
.callout-quiz-answer {
  --color1: #E8F2EA;
  --color2: #4A7C59;
  --border-color: #4A7C59;
  --background-color: rgba(74, 124, 89, 0.04);
  --title-background-color: rgba(74, 124, 89, 0.04);
  --dark-background-color: rgba(74, 124, 89, 0.12);
  --dark-title-background-color: rgba(74, 124, 89, 0.12);
}
.callout-example {
  --color1: #F0F8F6;
  --color2: #148F77;
  --border-color: #148F77;
  --background-color: rgba(20, 143, 119, 0.04);
  --title-background-color: rgba(20, 143, 119, 0.04);
  --dark-background-color: rgba(20, 143, 119, 0.12);
  --dark-title-background-color: rgba(20, 143, 119, 0.12);
}
.callout-colab {
  --color1: #FFF5E6;
  --color2: #FF6B35;
  --border-color: #FF6B35;
  --background-color: rgba(255, 107, 53, 0.04);
  --title-background-color: rgba(255, 107, 53, 0.04);
  --dark-background-color: rgba(255, 107, 53, 0.12);
  --dark-title-background-color: rgba(255, 107, 53, 0.12);
}
.callout-notebook {
  --color1: #F4F7FA;
  --color2: #3F6077;
  --border-color: #3F6077;
  --background-color: rgba(63, 96, 119, 0.04);
  --title-background-color: rgba(63, 96, 119, 0.04);
  --dark-background-color: rgba(63, 96, 119, 0.12);
  --dark-title-background-color: rgba(63, 96, 119, 0.12);
}
.callout-war-story {
  --color1: #FEF2F2;
  --color2: #C53030;
  --border-color: #C53030;
  --background-color: rgba(197, 48, 48, 0.04);
  --title-background-color: rgba(197, 48, 48, 0.04);
  --dark-background-color: rgba(197, 48, 48, 0.12);
  --dark-title-background-color: rgba(197, 48, 48, 0.12);
}
.callout-learning-objectives {
  --color1: #E8F2EA;
  --color2: #4A7C59;
  --border-color: #4A7C59;
  --background-color: rgba(74, 124, 89, 0.04);
  --title-background-color: rgba(74, 124, 89, 0.04);
  --dark-background-color: rgba(74, 124, 89, 0.12);
  --dark-title-background-color: rgba(74, 124, 89, 0.12);
}
</style>
<style>
@media (prefers-color-scheme: dark) {
  details.callout-definition {
    --text-color: #e6e6e6;
    --background-color: rgba(79, 115, 150, 0.12);
    --title-background-color: rgba(79, 115, 150, 0.12);
    border-color: #4F7396;
  }
  details.callout-definition summary,
  details.callout-definition summary strong,
  details.callout-definition > summary {
    color: #f0f0f0 !important;
  }
  details.callout-definition code {
    color: #e6e6e6 !important;
  }
  details.callout-chapter-connection {
    --text-color: #e6e6e6;
    --background-color: rgba(100, 116, 139, 0.12);
    --title-background-color: rgba(100, 116, 139, 0.12);
    border-color: #64748B;
  }
  details.callout-chapter-connection summary,
  details.callout-chapter-connection summary strong,
  details.callout-chapter-connection > summary {
    color: #f0f0f0 !important;
  }
  details.callout-chapter-connection code {
    color: #e6e6e6 !important;
  }
  details.callout-case-study {
    --text-color: #e6e6e6;
    --background-color: rgba(197, 48, 48, 0.12);
    --title-background-color: rgba(197, 48, 48, 0.12);
    border-color: #C53030;
  }
  details.callout-case-study summary,
  details.callout-case-study summary strong,
  details.callout-case-study > summary {
    color: #f0f0f0 !important;
  }
  details.callout-case-study code {
    color: #e6e6e6 !important;
  }
  details.callout-principle {
    --text-color: #e6e6e6;
    --background-color: rgba(61, 59, 142, 0.12);
    --title-background-color: rgba(61, 59, 142, 0.12);
    border-color: #3D3B8E;
  }
  details.callout-principle summary,
  details.callout-principle summary strong,
  details.callout-principle > summary {
    color: #f0f0f0 !important;
  }
  details.callout-principle code {
    color: #e6e6e6 !important;
  }
  details.callout-theorem {
    --text-color: #e6e6e6;
    --background-color: rgba(107, 70, 193, 0.12);
    --title-background-color: rgba(107, 70, 193, 0.12);
    border-color: #6B46C1;
  }
  details.callout-theorem summary,
  details.callout-theorem summary strong,
  details.callout-theorem > summary {
    color: #f0f0f0 !important;
  }
  details.callout-theorem code {
    color: #e6e6e6 !important;
  }
  details.callout-lighthouse {
    --text-color: #e6e6e6;
    --background-color: rgba(184, 134, 11, 0.12);
    --title-background-color: rgba(184, 134, 11, 0.12);
    border-color: #B8860B;
  }
  details.callout-lighthouse summary,
  details.callout-lighthouse summary strong,
  details.callout-lighthouse > summary {
    color: #f0f0f0 !important;
  }
  details.callout-lighthouse code {
    color: #e6e6e6 !important;
  }
  details.callout-research-questions {
    --text-color: #e6e6e6;
    --background-color: rgba(91, 75, 138, 0.12);
    --title-background-color: rgba(91, 75, 138, 0.12);
    border-color: #5B4B8A;
  }
  details.callout-research-questions summary,
  details.callout-research-questions summary strong,
  details.callout-research-questions > summary {
    color: #f0f0f0 !important;
  }
  details.callout-research-questions code {
    color: #e6e6e6 !important;
  }
  details.callout-quiz-question {
    --text-color: #e6e6e6;
    --background-color: rgba(91, 75, 138, 0.12);
    --title-background-color: rgba(91, 75, 138, 0.12);
    border-color: #5B4B8A;
  }
  details.callout-quiz-question summary,
  details.callout-quiz-question summary strong,
  details.callout-quiz-question > summary {
    color: #f0f0f0 !important;
  }
  details.callout-quiz-question code {
    color: #e6e6e6 !important;
  }
  details.callout-resource-exercises {
    --text-color: #e6e6e6;
    --background-color: rgba(32, 178, 170, 0.12);
    --title-background-color: rgba(32, 178, 170, 0.12);
    border-color: #20B2AA;
  }
  details.callout-resource-exercises summary,
  details.callout-resource-exercises summary strong,
  details.callout-resource-exercises > summary {
    color: #f0f0f0 !important;
  }
  details.callout-resource-exercises code {
    color: #e6e6e6 !important;
  }
  details.callout-perspective {
    --text-color: #e6e6e6;
    --background-color: rgba(74, 85, 104, 0.12);
    --title-background-color: rgba(74, 85, 104, 0.12);
    border-color: #4A5568;
  }
  details.callout-perspective summary,
  details.callout-perspective summary strong,
  details.callout-perspective > summary {
    color: #f0f0f0 !important;
  }
  details.callout-perspective code {
    color: #e6e6e6 !important;
  }
  details.callout-resource-videos {
    --text-color: #e6e6e6;
    --background-color: rgba(32, 178, 170, 0.12);
    --title-background-color: rgba(32, 178, 170, 0.12);
    border-color: #20B2AA;
  }
  details.callout-resource-videos summary,
  details.callout-resource-videos summary strong,
  details.callout-resource-videos > summary {
    color: #f0f0f0 !important;
  }
  details.callout-resource-videos code {
    color: #e6e6e6 !important;
  }
  details.callout-checkpoint {
    --text-color: #e6e6e6;
    --background-color: rgba(77, 124, 15, 0.12);
    --title-background-color: rgba(77, 124, 15, 0.12);
    border-color: #4D7C0F;
  }
  details.callout-checkpoint summary,
  details.callout-checkpoint summary strong,
  details.callout-checkpoint > summary {
    color: #f0f0f0 !important;
  }
  details.callout-checkpoint code {
    color: #e6e6e6 !important;
  }
  details.callout-takeaways {
    --text-color: #e6e6e6;
    --background-color: rgba(157, 60, 114, 0.12);
    --title-background-color: rgba(157, 60, 114, 0.12);
    border-color: #9D3C72;
  }
  details.callout-takeaways summary,
  details.callout-takeaways summary strong,
  details.callout-takeaways > summary {
    color: #f0f0f0 !important;
  }
  details.callout-takeaways code {
    color: #e6e6e6 !important;
  }
  details.callout-resource-slides {
    --text-color: #e6e6e6;
    --background-color: rgba(32, 178, 170, 0.12);
    --title-background-color: rgba(32, 178, 170, 0.12);
    border-color: #20B2AA;
  }
  details.callout-resource-slides summary,
  details.callout-resource-slides summary strong,
  details.callout-resource-slides > summary {
    color: #f0f0f0 !important;
  }
  details.callout-resource-slides code {
    color: #e6e6e6 !important;
  }
  details.callout-code {
    --text-color: #e6e6e6;
    --background-color: rgba(60, 72, 88, 0.12);
    --title-background-color: rgba(60, 72, 88, 0.12);
    border-color: #3C4858;
  }
  details.callout-code summary,
  details.callout-code summary strong,
  details.callout-code > summary {
    color: #f0f0f0 !important;
  }
  details.callout-code code {
    color: #e6e6e6 !important;
  }
  details.callout-quiz-answer {
    --text-color: #e6e6e6;
    --background-color: rgba(74, 124, 89, 0.12);
    --title-background-color: rgba(74, 124, 89, 0.12);
    border-color: #4A7C59;
  }
  details.callout-quiz-answer summary,
  details.callout-quiz-answer summary strong,
  details.callout-quiz-answer > summary {
    color: #f0f0f0 !important;
  }
  details.callout-quiz-answer code {
    color: #e6e6e6 !important;
  }
  details.callout-example {
    --text-color: #e6e6e6;
    --background-color: rgba(20, 143, 119, 0.12);
    --title-background-color: rgba(20, 143, 119, 0.12);
    border-color: #148F77;
  }
  details.callout-example summary,
  details.callout-example summary strong,
  details.callout-example > summary {
    color: #f0f0f0 !important;
  }
  details.callout-example code {
    color: #e6e6e6 !important;
  }
  details.callout-colab {
    --text-color: #e6e6e6;
    --background-color: rgba(255, 107, 53, 0.12);
    --title-background-color: rgba(255, 107, 53, 0.12);
    border-color: #FF6B35;
  }
  details.callout-colab summary,
  details.callout-colab summary strong,
  details.callout-colab > summary {
    color: #f0f0f0 !important;
  }
  details.callout-colab code {
    color: #e6e6e6 !important;
  }
  details.callout-notebook {
    --text-color: #e6e6e6;
    --background-color: rgba(63, 96, 119, 0.12);
    --title-background-color: rgba(63, 96, 119, 0.12);
    border-color: #3F6077;
  }
  details.callout-notebook summary,
  details.callout-notebook summary strong,
  details.callout-notebook > summary {
    color: #f0f0f0 !important;
  }
  details.callout-notebook code {
    color: #e6e6e6 !important;
  }
  details.callout-war-story {
    --text-color: #e6e6e6;
    --background-color: rgba(197, 48, 48, 0.12);
    --title-background-color: rgba(197, 48, 48, 0.12);
    border-color: #C53030;
  }
  details.callout-war-story summary,
  details.callout-war-story summary strong,
  details.callout-war-story > summary {
    color: #f0f0f0 !important;
  }
  details.callout-war-story code {
    color: #e6e6e6 !important;
  }
  details.callout-learning-objectives {
    --text-color: #e6e6e6;
    --background-color: rgba(74, 124, 89, 0.12);
    --title-background-color: rgba(74, 124, 89, 0.12);
    border-color: #4A7C59;
  }
  details.callout-learning-objectives summary,
  details.callout-learning-objectives summary strong,
  details.callout-learning-objectives > summary {
    color: #f0f0f0 !important;
  }
  details.callout-learning-objectives code {
    color: #e6e6e6 !important;
  }
}
body.quarto-dark details.callout-definition {
    --text-color: #e6e6e6;
    --background-color: rgba(79, 115, 150, 0.12);
    --title-background-color: rgba(79, 115, 150, 0.12);
    border-color: #4F7396;
  }
body.quarto-dark details.callout-definition summary,
body.quarto-dark details.callout-definition summary strong,
body.quarto-dark details.callout-definition > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-definition code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-chapter-connection {
    --text-color: #e6e6e6;
    --background-color: rgba(100, 116, 139, 0.12);
    --title-background-color: rgba(100, 116, 139, 0.12);
    border-color: #64748B;
  }
body.quarto-dark details.callout-chapter-connection summary,
body.quarto-dark details.callout-chapter-connection summary strong,
body.quarto-dark details.callout-chapter-connection > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-chapter-connection code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-case-study {
    --text-color: #e6e6e6;
    --background-color: rgba(197, 48, 48, 0.12);
    --title-background-color: rgba(197, 48, 48, 0.12);
    border-color: #C53030;
  }
body.quarto-dark details.callout-case-study summary,
body.quarto-dark details.callout-case-study summary strong,
body.quarto-dark details.callout-case-study > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-case-study code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-principle {
    --text-color: #e6e6e6;
    --background-color: rgba(61, 59, 142, 0.12);
    --title-background-color: rgba(61, 59, 142, 0.12);
    border-color: #3D3B8E;
  }
body.quarto-dark details.callout-principle summary,
body.quarto-dark details.callout-principle summary strong,
body.quarto-dark details.callout-principle > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-principle code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-theorem {
    --text-color: #e6e6e6;
    --background-color: rgba(107, 70, 193, 0.12);
    --title-background-color: rgba(107, 70, 193, 0.12);
    border-color: #6B46C1;
  }
body.quarto-dark details.callout-theorem summary,
body.quarto-dark details.callout-theorem summary strong,
body.quarto-dark details.callout-theorem > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-theorem code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-lighthouse {
    --text-color: #e6e6e6;
    --background-color: rgba(184, 134, 11, 0.12);
    --title-background-color: rgba(184, 134, 11, 0.12);
    border-color: #B8860B;
  }
body.quarto-dark details.callout-lighthouse summary,
body.quarto-dark details.callout-lighthouse summary strong,
body.quarto-dark details.callout-lighthouse > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-lighthouse code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-research-questions {
    --text-color: #e6e6e6;
    --background-color: rgba(91, 75, 138, 0.12);
    --title-background-color: rgba(91, 75, 138, 0.12);
    border-color: #5B4B8A;
  }
body.quarto-dark details.callout-research-questions summary,
body.quarto-dark details.callout-research-questions summary strong,
body.quarto-dark details.callout-research-questions > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-research-questions code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-quiz-question {
    --text-color: #e6e6e6;
    --background-color: rgba(91, 75, 138, 0.12);
    --title-background-color: rgba(91, 75, 138, 0.12);
    border-color: #5B4B8A;
  }
body.quarto-dark details.callout-quiz-question summary,
body.quarto-dark details.callout-quiz-question summary strong,
body.quarto-dark details.callout-quiz-question > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-quiz-question code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-resource-exercises {
    --text-color: #e6e6e6;
    --background-color: rgba(32, 178, 170, 0.12);
    --title-background-color: rgba(32, 178, 170, 0.12);
    border-color: #20B2AA;
  }
body.quarto-dark details.callout-resource-exercises summary,
body.quarto-dark details.callout-resource-exercises summary strong,
body.quarto-dark details.callout-resource-exercises > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-resource-exercises code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-perspective {
    --text-color: #e6e6e6;
    --background-color: rgba(74, 85, 104, 0.12);
    --title-background-color: rgba(74, 85, 104, 0.12);
    border-color: #4A5568;
  }
body.quarto-dark details.callout-perspective summary,
body.quarto-dark details.callout-perspective summary strong,
body.quarto-dark details.callout-perspective > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-perspective code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-resource-videos {
    --text-color: #e6e6e6;
    --background-color: rgba(32, 178, 170, 0.12);
    --title-background-color: rgba(32, 178, 170, 0.12);
    border-color: #20B2AA;
  }
body.quarto-dark details.callout-resource-videos summary,
body.quarto-dark details.callout-resource-videos summary strong,
body.quarto-dark details.callout-resource-videos > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-resource-videos code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-checkpoint {
    --text-color: #e6e6e6;
    --background-color: rgba(77, 124, 15, 0.12);
    --title-background-color: rgba(77, 124, 15, 0.12);
    border-color: #4D7C0F;
  }
body.quarto-dark details.callout-checkpoint summary,
body.quarto-dark details.callout-checkpoint summary strong,
body.quarto-dark details.callout-checkpoint > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-checkpoint code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-takeaways {
    --text-color: #e6e6e6;
    --background-color: rgba(157, 60, 114, 0.12);
    --title-background-color: rgba(157, 60, 114, 0.12);
    border-color: #9D3C72;
  }
body.quarto-dark details.callout-takeaways summary,
body.quarto-dark details.callout-takeaways summary strong,
body.quarto-dark details.callout-takeaways > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-takeaways code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-resource-slides {
    --text-color: #e6e6e6;
    --background-color: rgba(32, 178, 170, 0.12);
    --title-background-color: rgba(32, 178, 170, 0.12);
    border-color: #20B2AA;
  }
body.quarto-dark details.callout-resource-slides summary,
body.quarto-dark details.callout-resource-slides summary strong,
body.quarto-dark details.callout-resource-slides > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-resource-slides code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-code {
    --text-color: #e6e6e6;
    --background-color: rgba(60, 72, 88, 0.12);
    --title-background-color: rgba(60, 72, 88, 0.12);
    border-color: #3C4858;
  }
body.quarto-dark details.callout-code summary,
body.quarto-dark details.callout-code summary strong,
body.quarto-dark details.callout-code > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-code code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-quiz-answer {
    --text-color: #e6e6e6;
    --background-color: rgba(74, 124, 89, 0.12);
    --title-background-color: rgba(74, 124, 89, 0.12);
    border-color: #4A7C59;
  }
body.quarto-dark details.callout-quiz-answer summary,
body.quarto-dark details.callout-quiz-answer summary strong,
body.quarto-dark details.callout-quiz-answer > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-quiz-answer code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-example {
    --text-color: #e6e6e6;
    --background-color: rgba(20, 143, 119, 0.12);
    --title-background-color: rgba(20, 143, 119, 0.12);
    border-color: #148F77;
  }
body.quarto-dark details.callout-example summary,
body.quarto-dark details.callout-example summary strong,
body.quarto-dark details.callout-example > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-example code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-colab {
    --text-color: #e6e6e6;
    --background-color: rgba(255, 107, 53, 0.12);
    --title-background-color: rgba(255, 107, 53, 0.12);
    border-color: #FF6B35;
  }
body.quarto-dark details.callout-colab summary,
body.quarto-dark details.callout-colab summary strong,
body.quarto-dark details.callout-colab > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-colab code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-notebook {
    --text-color: #e6e6e6;
    --background-color: rgba(63, 96, 119, 0.12);
    --title-background-color: rgba(63, 96, 119, 0.12);
    border-color: #3F6077;
  }
body.quarto-dark details.callout-notebook summary,
body.quarto-dark details.callout-notebook summary strong,
body.quarto-dark details.callout-notebook > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-notebook code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-war-story {
    --text-color: #e6e6e6;
    --background-color: rgba(197, 48, 48, 0.12);
    --title-background-color: rgba(197, 48, 48, 0.12);
    border-color: #C53030;
  }
body.quarto-dark details.callout-war-story summary,
body.quarto-dark details.callout-war-story summary strong,
body.quarto-dark details.callout-war-story > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-war-story code {
    color: #e6e6e6 !important;
  }
body.quarto-dark details.callout-learning-objectives {
    --text-color: #e6e6e6;
    --background-color: rgba(74, 124, 89, 0.12);
    --title-background-color: rgba(74, 124, 89, 0.12);
    border-color: #4A7C59;
  }
body.quarto-dark details.callout-learning-objectives summary,
body.quarto-dark details.callout-learning-objectives summary strong,
body.quarto-dark details.callout-learning-objectives > summary {
    color: #f0f0f0 !important;
  }
body.quarto-dark details.callout-learning-objectives code {
    color: #e6e6e6 !important;
  }
</style>
<style>
details.callout-definition > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_definition.png");
}
details.callout-chapter-connection > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_chapter_connection.png");
}
details.callout-case-study > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_case_study.png");
}
details.callout-principle > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_principle.png");
}
details.callout-theorem > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_theorem.png");
}
details.callout-lighthouse > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_lighthouse.png");
}
details.callout-research-questions > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_research_questions.png");
}
details.callout-quiz-question > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_quiz_question.png");
}
details.callout-resource-exercises > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_resource_exercises.png");
}
details.callout-perspective > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_perspective.png");
}
details.callout-resource-videos > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_resource_videos.png");
}
details.callout-checkpoint > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_checkpoint.png");
}
details.callout-takeaways > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_takeaways.png");
}
details.callout-resource-slides > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_resource_slides.png");
}
details.callout-code > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_code.png");
}
details.callout-quiz-answer > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_quiz_answer.png");
}
details.callout-example > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_example.png");
}
details.callout-colab > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_colab.png");
}
details.callout-notebook > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_notebook.png");
}
details.callout-war-story > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_case_study.png");
}
details.callout-learning-objectives > summary::before {
  background-image: url("../shared/assets/images/icons/callouts/icon_callout_learning_objectives.png");
}
</style>
    <style type="text/css">
    .ps-root .ps-algorithm {
      border-top: 2px solid;
      border-bottom: 2px solid;
    }
    .pseudocode-container {
      text-align: left;
    }
    </style>
  
      <style type="text/css">
      .ps-algorithm > .ps-line {
        text-align: left;
      }
      </style>
    

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Physical AI">
<meta property="og:image" content="../17_frontier/vol4/covers/cover-hardcover-book-vol4.png">
<meta property="og:site_name" content="Physical AI">
<meta property="og:locale" content="en_US">
<meta name="twitter:title" content="Physical AI">
<meta name="twitter:image" content="../17_frontier/vol4/covers/cover-hardcover-book-vol4.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating nav-fixed slimcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-xl " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo" aria-label="Machine Learning Systems home">
    <img src="../shared/assets/images/icons/logo-seas-shield.png" alt="" class="navbar-logo light-content">
    <img src="../shared/assets/images/icons/logo-seas-shield.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Machine Learning Systems</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-read" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Read</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-read">    
        <li>
    <a class="dropdown-item" href="../../vol1/"><i class="bi bi-journal" role="img">
</i> 
 <span class="dropdown-text">Volume I: Foundations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../vol2/"><i class="bi bi-journal" role="img">
</i> 
 <span class="dropdown-text">Volume II: Scaling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../vol3/"><i class="bi bi-journal" role="img">
</i> 
 <span class="dropdown-text">Volume III: Agentic (Draft)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../"><i class="bi bi-journal" role="img">
</i> 
 <span class="dropdown-text">Volume IV: Physical AI (Draft)</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/tinytorch/"><i class="bi bi-fire" role="img">
</i> 
 <span class="dropdown-text">TinyTorch (Standalone Book)</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../vol1/assets/downloads/Machine-Learning-Systems-Vol1.pdf" target="_blank"><i class="bi bi-file-pdf" role="img">
</i> 
 <span class="dropdown-text">Volume I PDF</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../vol1/assets/downloads/Machine-Learning-Systems-Vol1.epub" target="_blank"><i class="bi bi-book" role="img">
</i> 
 <span class="dropdown-text">Volume I EPUB</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../vol2/assets/downloads/Machine-Learning-Systems-Vol2.pdf" target="_blank"><i class="bi bi-file-pdf" role="img">
</i> 
 <span class="dropdown-text">Volume II PDF</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../vol2/assets/downloads/Machine-Learning-Systems-Vol2.epub" target="_blank"><i class="bi bi-book" role="img">
</i> 
 <span class="dropdown-text">Volume II EPUB</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../vol3/assets/downloads/Machine-Learning-Systems-Vol3.pdf" target="_blank"><i class="bi bi-file-pdf" role="img">
</i> 
 <span class="dropdown-text">Volume III PDF</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../vol3/assets/downloads/Machine-Learning-Systems-Vol3.epub" target="_blank"><i class="bi bi-book" role="img">
</i> 
 <span class="dropdown-text">Volume III EPUB</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../assets/downloads/Machine-Learning-Systems-Vol4.pdf" target="_blank"><i class="bi bi-file-pdf" role="img">
</i> 
 <span class="dropdown-text">Volume IV PDF</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../assets/downloads/Machine-Learning-Systems-Vol4.epub" target="_blank"><i class="bi bi-book" role="img">
</i> 
 <span class="dropdown-text">Volume IV EPUB</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-build" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Build</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-build">    
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/games/"><i class="bi bi-controller" role="img">
</i> 
 <span class="dropdown-text">Playground Games</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/labs/"><i class="bi bi-sliders" role="img">
</i> 
 <span class="dropdown-text">Labs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/tinytorch/"><i class="bi bi-fire" role="img">
</i> 
 <span class="dropdown-text">TinyTorch</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/kits/"><i class="bi bi-cpu" role="img">
</i> 
 <span class="dropdown-text">Hardware Kits</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/mlsysim/"><i class="bi bi-calculator" role="img">
</i> 
 <span class="dropdown-text">MLSys·im</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-teach" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Teach</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-teach">    
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/instructors/course-map.html"><i class="bi bi-signpost-split" role="img">
</i> 
 <span class="dropdown-text">CS249r Course Map</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/slides/"><i class="bi bi-easel" role="img">
</i> 
 <span class="dropdown-text">Lecture Slides</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/instructors/"><i class="bi bi-person-video3" role="img">
</i> 
 <span class="dropdown-text">Instructor Hub</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/community/courses.html"><i class="bi bi-mortarboard" role="img">
</i> 
 <span class="dropdown-text">Courses Using the Book</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-prepare" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Prepare</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-prepare">    
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/staffml/"><i class="bi bi-mortarboard" role="img">
</i> 
 <span class="dropdown-text">StaffML</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/staffml/plans"><i class="bi bi-map" role="img">
</i> 
 <span class="dropdown-text">Study Plans</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/staffml/gauntlet"><i class="bi bi-lightning" role="img">
</i> 
 <span class="dropdown-text">Gauntlet Mode</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/staffml/downloads/StaffML-Paper.pdf" target="_blank"><i class="bi bi-file-pdf" role="img">
</i> 
 <span class="dropdown-text">StaffML Paper</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-connect" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Connect</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-connect">    
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/newsletter/"><i class="bi bi-envelope" role="img">
</i> 
 <span class="dropdown-text">Newsletter</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/community/"><i class="bi bi-globe" role="img">
</i> 
 <span class="dropdown-text">Global Network</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/community/events.html"><i class="bi bi-calendar-event" role="img">
</i> 
 <span class="dropdown-text">Workshops &amp; Events</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/community/partners.html"><i class="bi bi-people" role="img">
</i> 
 <span class="dropdown-text">Partners &amp; Sponsors</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/about/"><i class="bi bi-bullseye" role="img">
</i> 
 <span class="dropdown-text">Mission</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/about/#story"><i class="bi bi-book" role="img">
</i> 
 <span class="dropdown-text">Our Story</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/about/people.html"><i class="bi bi-person-lines-fill" role="img">
</i> 
 <span class="dropdown-text">People</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/about/contributors.html"><i class="bi bi-people" role="img">
</i> 
 <span class="dropdown-text">Contributors</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://mlsysbook.ai/about/license.html"><i class="bi bi-cc-circle" role="img">
</i> 
 <span class="dropdown-text">License</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mlsysbook.ai/newsletter/"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text">Subscribe</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/harvard-edge/cs249r_book" target="_blank"> <i class="bi bi-star" role="img">
</i> 
<span class="menu-text">Star</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://opencollective.com/mlsysbook" target="_blank"> <i class="bi bi-heart" role="img">
</i> 
<span class="menu-text">Support</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-github" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text">GitHub</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-github">    
        <li>
    <a class="dropdown-item" href="https://github.com/harvard-edge/cs249r_book/discussions" target="_blank"><i class="bi bi-chat" role="img">
</i> 
 <span class="dropdown-text">Discussions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/harvard-edge/cs249r_book" target="_blank"><i class="bi bi-pencil" role="img">
</i> 
 <span class="dropdown-text">Edit this page</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/harvard-edge/cs249r_book/issues/new" target="_blank"><i class="bi bi-bug" role="img">
</i> 
 <span class="dropdown-text">Report an issue</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/harvard-edge/cs249r_book" target="_blank"><i class="bi bi-code" role="img">
</i> 
 <span class="dropdown-text">View source</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="17_frontier.html">Conclusion: The Epistemic Frontier</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
  <div id="quarto-announcement" data-announcement-id="b2935f446d2c70649ebc581c97c2e754" class="alert alert-primary hidden"><i class="bi bi-megaphone quarto-announcement-icon"></i><div class="quarto-announcement-content">
<p style="margin: 0 0 12px 0; padding: 8px 12px; background: rgba(255,193,7,0.2); border: 1px solid #ffc107; border-radius: 4px; font-weight: 600;"><i class="bi bi-exclamation-triangle-fill" style="margin-right: 6px; color: #856404;"></i><strong>🚧 DEVELOPMENT PREVIEW</strong> - Built from dev@<code style="background: rgba(0,0,0,0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em;">3dd32850</code> • 2026-09-22 16:55 EDT • <a href="https://mlsysbook.ai" style="color: #856404; text-decoration: underline;"><em>Stable version →</em></a></p>
<p>🌲 <strong>DRAFT — Volume IV: Physical AI Systems.</strong> Work in progress · Early evolving draft ahead of target release in late 2027 / early 2028.<br> 📘 <strong>Foundations:</strong> <a href="../../vol1/">Volume I: Foundations</a> · <a href="../../vol2/">Volume II: Scaling</a> · <a href="../../vol3/">Volume III: Agentic</a><br> 🛠️ <strong>Alongside the book:</strong> <a href="https://mlsysbook.ai/tinytorch/">TinyTorch</a> (build) · <a href="https://mlsysbook.ai/kits/">Hardware Kits</a> (deploy) · <a href="https://mlsysbook.ai/mlsysim/">MLSys·im</a> (model) · <a href="https://mlsysbook.ai/labs/">Labs</a> (explore)<br> 📬 <strong>Newsletter:</strong> ML Systems insights &amp; updates — <a href="https://mlsysbook.ai/newsletter/">Subscribe →</a></p>
</div></div>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homepage</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/dedication.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dedication</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/author_note.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Author’s Note</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/about_author.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About the Author</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/prerequisites.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reader Guide and Prerequisites</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/acknowledgements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgments</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/ai_use.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A Note on AI Assistance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../frontmatter/notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notation</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01_boundary/01_boundary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction: The Causal Boundary</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/anatomy_principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part I: The Machine Anatomy</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_body/02_body.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Physical Body</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../03_brain/03_brain.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Cognitive Brain</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../04_nervous/04_nervous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Nervous System</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/teaching_principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part II: Teaching the Machine</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../05_data/05_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Physical Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../06_training/06_training.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Policy Training</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../07_evaluation/07_evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Closed-Loop Evaluation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/running_principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part III: Running the Machine</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../08_perception/08_perception.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sensor Perception</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../09_memory/09_memory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spatial Memory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../10_intent/10_intent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grounded Intent</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../11_planning/11_planning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Trajectory Planning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../12_enforcement/12_enforcement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Safety Enforcement</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../13_placement/13_placement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Silicon Placement</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/governing_principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part IV: Governing the Machine</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../14_intervention/14_intervention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Supervisory Intervention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../15_verification/15_verification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Adversarial Verification</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../16_release/16_release.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deployment Release</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="17_frontier.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Conclusion: The Epistemic Frontier</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../backmatter/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../backmatter/appendix_ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Machine Learning Background</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../backmatter/appendix_control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Control and Dynamics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../backmatter/appendix_systems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Systems and Hardware</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../backmatter/appendix_spa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">S·P·A Diagnostic Playbook</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../backmatter/glossary/glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><h1 class="title display-7">The Epistemic Frontier</h1></header>


<header id="title-block-header">


</header>


<section id="sec-frontier" class="level1 page-columns page-full">
<h1>The Epistemic Frontier</h1>
<div class="{layout-narrow} page-columns page-full">

<div class="no-row-height column-margin column-container"><div class="">

</div></div><p><a href="images/webp/cover_frontier_blueprint_labeled.webp" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="images/webp/cover_frontier_blueprint_labeled.webp" class="img-fluid" alt="Isometric blueprint of the epistemic frontier: a layered physical AI stack under glass, a red containment barrier at the edge of a chasm labeled unobserved reality, and an amber prism projecting a diagnostic beam across it."></a></p>
</div>
<section id="purpose" class="level2 unnumbered unlisted page-columns page-full">
<h2 class="unnumbered unlisted anchored" data-anchor-id="purpose">Purpose</h2>
<p><em>How much authority can a machine hold when evidence cannot settle every premise its safety rests on?</em></p>
<p>The opening chapter asked what guarantees a machine must enforce before a learned proposal commands physical work. The preceding chapters established the architectural answer: an independent real-time permission path deciding on bounded-age evidence, operating strictly within margins unconsumed by latency, and backed by a verified stopping fallback. Yet every formal guarantee remains conditional on unmeasured physical premises.</p>
<p>A braking certificate assumes a minimum surface friction coefficient that onboard sensors cannot measure prior to contact; a barrier filter assumes uncorrupted state estimation and nominal actuator torque; and a deployment release assumes environmental bounds tested across finite exposure. When rare hazards elude empirical observation, engineering integrity demands naming each unverified premise and restricting operational authority rather than assuming safety by default. Because the causal boundary never relaxes when evidence runs out, autonomous authority must terminate precisely where physical evidence ends.</p>

<div class="no-row-height column-margin column-container"><div class="margin-pointer">
<p>↰ <strong>Prerequisite:</strong> The four laws of <strong><a href="../01_boundary/01_boundary.html#sec-boundary-bedrock-laws">The Four Bedrock Laws</a></strong>, which this chapter closes on.</p>
</div></div><div style="page-break-after: always;"></div>
<div id="callout-learning-objectives*-1.1" class="callout callout-learning-objectives">
<details class="callout-learning-objectives fbx-simplebox fbx-default" open=""><summary><strong>Learning Objectives</strong></summary><div>
<ul>
<li>Assess which safety claims exceed the evidence available for a specific physical machine</li>
<li>Evaluate whether a detector can identify a hazard before effective intervention becomes impossible</li>
<li>Construct residual-claims register entries, each with a restriction, an owner, and a sized closure test, from a release’s open premises</li>
<li>Classify an open premise by the missing observable, evaluation, theory, or scope that would close it</li>
<li>Trace the four bedrock laws through an unfamiliar machine and state which premise of each the evidence leaves open</li>
</ul>
</div></details>
</div>
</section>
<section id="sec-frontier-epistemic-limits" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-frontier-epistemic-limits">Epistemic Limits</h2>
<p>Every engineering method has an epistemic boundary where its formal guarantees expire. In physical AI, that boundary is not merely an algorithmic shortfall; it is a physical confrontation between compute latency, sensory observability, and mechanical inertia. Scaling the parameter count of foundation models can yield extraordinary semantic breadth, but it cannot bend the laws of motion: as networks grow, inference latency expands the reaction corridor, trading agility for deliberative depth.</p>
<div id="dfn-frontier-embodied-latency-scaling-law" class="callout callout-definition" title="Embodied latency scaling law">
<details class="callout-definition fbx-simplebox fbx-default" open=""><summary><strong>Definition 1.1: Embodied latency scaling law</strong></summary><div>
<p><strong><em>Embodied latency scaling law</em></strong> is the physical constraint dictating that scaling neural policy parameter count yields diminishing operational safety returns unless inference latency decreases proportionally, because physical reaction distance <span class="math inline">\(d_{\text{react}} = v \cdot (t_{\text{inference}} + t_{\text{actuation}}) + \frac{v^2}{2 a_{\max}}\)</span> scales linearly with computational delay.</p>
<ol type="1">
<li><strong>Significance</strong>: Establishes that intelligence in physical systems cannot be scaled purely by adding model parameters, because computational delay directly degrades dynamic stability and spatial stopping clearance.</li>
<li><strong>Distinction</strong>: Unlike compute scaling laws in static language modeling where latency affects only token generation speed, embodied latency scaling directly couples computational delay to mechanical reaction time constants (<span class="math inline">\(t_{\text{react}} \ge t_{\text{inference}} + t_{\text{actuation}}\)</span>).</li>
<li><strong>Common pitfall</strong>: Deploying multi-billion parameter foundation models directly in the closed-loop control path under the assumption that greater semantic reasoning compensates for an unbudgeted response delay.</li>
</ol>
</div></details>
</div>
<p>This tension, codified in <a href="#dfn-frontier-embodied-latency-scaling-law">1.1</a>, illustrates why parameter scaling alone cannot solve real-time safety. Furthermore, as governed by Ashby’s Law of Requisite Variety <span class="citation" data-cites="ashby1956introduction">(<a href="#ref-ashby1956introduction" role="doc-biblioref">Ashby 1956</a>)</span>, a controller cannot regulate disturbances that its sensory architecture cannot perceive. When an unmodeled disturbance enters the physical plant, no amount of latent computation can compensate for missing physical evidence.</p>
<div class="no-row-height column-margin column-container"></div><p>A pallet jack with a weeping hydraulic line crosses one aisle of the site where the warehouse mobile manipulator works, and it leaves a clear film of fluid on the concrete. The machine’s stopping budget assumes that the floor can supply the friction its credible deceleration needs, and on dry concrete it can. Under the film it may not, and neither the navigation camera nor the lidar can tell the film from dry floor. The permission path can meet every deadline, the chunk lease can expire on time, and the brake can engage on schedule while the stop still runs past the rack end, because the term that failed is a premise that no sensor on the machine reports. The missing evidence is the local friction floor before braking begins.</p>
<p>The release decision of <strong><a href="../16_release/16_release.html#sec-release-safety-cases-claims">Safety Cases and Claims</a></strong> already met this premise. Its claim C3, braking traction, was refused on the book’s own evidence and handed to this chapter as an open premise. The machine’s credible deceleration is the smaller of what its brakes deliver and what the floor supplies, <span class="math inline">\(a = \min(a_{\text{brake}}, \mu g)\)</span>. The 2 m/s² credible deceleration that <strong><a href="../02_body/02_body.html#sec-body-kinetic-momentum">Kinetic Momentum</a></strong> set needs a friction coefficient of at least 0.204. Dry concrete, at a <span class="math inline">\(\mu\)</span> of 0.60, supplies far more, so the brakes bind. The clear film, at <span class="math inline">\(\mu\)</span> = 0.05 (both coefficients illustrative; see the Reader Guide), supplies only 0.49 m/s², and friction binds. At the 1.3 m/s aisle speed, the finished budget of <strong><a href="../12_enforcement/12_enforcement.html#tbl-enforcement-stopping-budget">The warehouse mobile manipulator's stopping budget</a></strong>, 997.4 mm on dry floor, grows on the film to 2.95 m against a 1.10 m clear distance. The friction premise did not become open when the film appeared. The normal mode that <strong><a href="../12_enforcement/12_enforcement.html#sec-enforcement-stopping-envelopes">Stopping Envelopes</a></strong> chose rested on that friction floor on every aisle, the dry ones included, and nothing had measured it there either.</p>
<p>Every engineering method has a boundary where its guarantees expire. The physical wall of <strong><a href="../01_boundary/01_boundary.html#sec-boundary-bedrock-laws">The Four Bedrock Laws</a></strong> is one such boundary, because a larger learned model cannot reduce the travel that its own delay costs the machine. Ashby’s law of requisite variety <span class="citation" data-cites="ashby1956introduction">(<a href="#ref-ashby1956introduction" role="doc-biblioref">Ashby 1956</a>)</span> names another, since a controller cannot regulate a disturbance that its sensors cannot perceive. On the mobile manipulator the oil film is such a disturbance. The arm’s contact limit at the door latch rests on a premise of the same kind, a latch that holds at every force below the arm’s contact ceiling, and corrosion or wear can lower the latch’s yield force below that ceiling while the joint torque sensors read exactly what they would read against a sound latch. A chemical flow regulator that holds line pressure below its limit depends on an undrifted pressure transducer, and deposition on the diaphragm can drift that reference until the loop regulates against a phantom reading while the true pressure exceeds the limit.</p>
<div class="no-row-height column-margin column-container"><div id="ref-ashby1956introduction" class="csl-entry" role="listitem">
Ashby, W Ross. 1956. <em>An Introduction to Cybernetics</em>. Chapman &amp; Hall.
</div></div><p>In each case the machine can leave its assumed conditions while its telemetry remains nominal. Successful trials cannot close such a gap, because the exposure wall that <strong><a href="../07_evaluation/07_evaluation.html#sec-evaluation-trial-limits">Physical Trial Limits</a></strong> derives places a rare-hazard rate beyond any practical failure-free campaign. The safety case must name the missing premise, restrict operation while it remains open, and state what evidence could close it. For each open premise, that discipline asks what the machine can measure, what its actuators can still prevent, and which claim must remain open.</p>
</section>
<section id="sec-frontier-method-limits" class="level2">
<h2 class="anchored" data-anchor-id="sec-frontier-method-limits">What the Method Cannot Establish</h2>
<p>The mobile manipulator’s release claim for the aisle is a chain of links, and which links it needs depends on the hazards and the protection chosen. The argument must establish the operating domain, measured actuator and stopping bounds, component contracts, and independent permission for learned proposals (<strong><a href="../01_boundary/01_boundary.html#sec-boundary-machine-model">The Machine in Five Levels</a></strong>). Hazards controlled by runtime detection also need measured detector coverage and timely monitoring. Hazards controlled by passive limits or operating restrictions instead need evidence that those measures hold over the declared load, wear, and exposure envelope. Generating extensive evidence for one link cannot compensate for an unsupported premise in another.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>Each premise of a safety case carries one of the Reader Guide’s five statuses (established by measurement or derivation, assumed, decided by accountable judgment, unsupported, or outside the threat model). The envelope trichotomy (<span class="math inline">\(\ref{dfn-release-envelope-trichotomy}\)</span>) places a premise that a runtime monitor checks as known-true, known-false, or unknown. The premises that bound the evidence here are ones no monitor now in service can check, so none can become known-true, and the release, not the monitor, must restrict operation around them. For the base, the stopping-distance claim relies on an assumed friction coefficient between wheel and floor that cannot be measured before braking begins. For the arm, the contact argument depends on a declared floor on the strength of the latch and the objects it handles, a floor decided by engineering judgment about structural yield, while the latch’s present strength stays unmeasured between proof tests. For the flow regulator, the pressure claim assumes a transducer whose zero point has not drifted, a premise that its own reading cannot check. Naming these premises explicitly does not weaken the release record. It establishes the physical envelope within which the release verdict is justified, and outside of which the verdict ceases to apply.</p>
<p>Separating measurement from judgment is fundamental to systems engineering discipline. Empirical testing and statistical characterization can estimate physical exposure, quantify sensor noise, and bound parametric uncertainty, but no measurement can choose an acceptable <strong>residual risk</strong> or decide which individuals in an operational environment must bear that risk. Those choices are accountable human decisions that must be recorded as explicit judgments rather than disguised as empirical findings. In the same way, the <strong>threat model</strong> bounds the validity of the record. Empirical testing across nominal fleet operations and accidental component faults provides no evidence regarding intentional adversarial attacks. A safety record demonstrating that a vision pipeline handles sensor noise, lens blur, and partial occlusions provides no statistical support for claims about resilience against adversarial optical projection, model parameter tampering, or intentional denial of service across the internal communication bus.</p>
<p>Take as the system target an illustrative <span class="math inline">\(10^{-9}\text{ h}^{-1}\)</span>, a rate that no standard assigns to this machine and that, by the exposure wall of <strong><a href="../07_evaluation/07_evaluation.html#sec-evaluation-trial-limits">Physical Trial Limits</a></strong>, operating hours alone cannot demonstrate.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> The remaining question is what the permission path can add to the claim when it acts between proposal and actuation as the safety shield of <strong><a href="../12_enforcement/12_enforcement.html#sec-enforcement-minimal-intervention">Minimal Intervention</a></strong>, and which of its premises need evidence of their own.</p>
<p>A shield argument is <em>conditional</em>, not a multiplication applied to observed system incidents. A fleet’s incident count cannot stand in for a proposal rate, because the hazardous proposals a shield prevented never appear in it. For a defined hazard class <span class="math inline">\(h\)</span>, let <span class="math inline">\(\lambda_{\mathrm{proposal},h}\)</span> be the rate of hazardous proposed actions before permission, and let <span class="math inline">\(c_h=P(\mathrm{intercept}\mid\mathrm{hazardous\ proposal},h)\)</span> be measured interception coverage for that class. With a separately bounded hardware and common-cause term <span class="math inline">\(\lambda_{\mathrm{other}}\)</span>, a model may use <a href="#eq-frontier-shielded-hazard" class="quarto-xref">equation&nbsp;1</a>: <span id="eq-frontier-shielded-hazard"><span class="math display">\[\lambda_{\mathrm{system},h} \le \lambda_{\mathrm{proposal},h}(1-c_h)+\lambda_{\mathrm{other}} \tag{1}\]</span></span> The relation requires a valid proposal oracle, timely detection, actuator authority, and a justified treatment of correlated failures. It gives no credit for an oil film or a weakened latch that the shield cannot observe, and no release follows from the arithmetic until each premise is supported.</p>
<div id="nbk-frontier-fleet-exposure-and-shielded-decomposition" class="callout callout-notebook" title="A conditional shield calculation">
<p></p><details class="callout-notebook fbx-simplebox fbx-default" open=""><summary><strong>Napkin Math 1.1: A conditional shield calculation</strong></summary><div><strong>Problem</strong>: One hundred robots keep a fully adjudicated proposal log for one 90-day cycle, judged by a validated counterfactual oracle, and the log records no hazardous proposal. If a named shield’s interception coverage for that hazard class were independently established at <span class="math inline">\(c=0.9999\)</span>, would the modeled residual meet the <span class="math inline">\(10^{-9}\text{ h}^{-1}\)</span> system target?<p></p>
<p><strong>Proposal bound</strong>: Under a stationary Poisson model, zero hazardous proposals in 2.16 × 10⁵ proposal-hours give a one-sided 95 percent upper bound of 1.387 × 10⁻⁵ <span class="math inline">\(\text{h}^{-1}\)</span>.</p>
<p><strong>Residual</strong>: With hardware and common-cause residual set to zero for this calculation, <a href="#eq-frontier-shielded-hazard" class="quarto-xref">equation&nbsp;1</a> gives 1.387 × 10⁻⁹ <span class="math inline">\(\text{h}^{-1}\)</span>, <strong>above</strong> the target. The coverage the target requires is at least 0.9999279.</p>
<p><strong>Required proposal evidence</strong>: At <span class="math inline">\(c=0.9999\)</span> the proposal-rate bound must fall to 1 × 10⁻⁵ <span class="math inline">\(\text{h}^{-1}\)</span>. Zero adjudicated hazardous proposals would then require 3.00 × 10⁵ proposal-hours, or 124.822 days for 100 units, 34.8 days beyond the cycle.</p>
<p><strong>Systems insight</strong>: A shield changes the system claim only for hazard classes it can detect and intercept in time. Proposal frequency, conditional interception coverage, hardware faults, and common-cause failures need separate evidence. Oil or material failure outside the shield’s sensing coverage stays in the residual-claims register.</p>
</div></details>
</div>
<p>Each of these premises, from friction under a film to a shield’s coverage for a hazard class it may not observe, ends the same way, named by the release and left unsettled by its evidence. A release that stops at naming them has only listed its caveats. What it needs is a record that turns each such premise into a restriction with an owner and a test that can end it.</p>
</section>
<section id="sec-frontier-residual-claims-register" class="level2">
<h2 class="anchored" data-anchor-id="sec-frontier-residual-claims-register">A Residual-Claims Register</h2>
<p>Refusing claim C3 did not remove the friction premise from the machine, and an unproven premise remains whether or not a safety report records it. The <strong>residual-claims register</strong> consumes the release manifest of <strong><a href="../16_release/16_release.html#sec-release-manifest">The Release Manifest</a></strong>, taking from it every premise the release left open or unsupported. An open entry restricts authority until its predeclared closure test passes. The register maps each such premise, and every unmonitored invariant, to its missing physical observable, its active containment or operating restriction, an accountable human owner, and a predeclared closure test. Without these four components, an unresolved premise is an unwritten risk, not a register entry. The register is where principle <span class="math inline">\(\ref{pri-vol4-evidence-bounds-authority}\)</span> reaches the premises that evidence could not settle, holding authority to a restriction wherever the supporting evidence is absent.</p>
<p>Each entry links the unsupported claim to the specific unmeasurable physical observable. In a machine that moves mass, a learned policy fails to settle a safety property because sensors cannot transduce the relevant environmental state, the computing substrate cannot process the measurement within the control deadline, or the physical interaction cannot be observed before contact occurs. An engineer must define the <strong>missing observable</strong> with physical precision rather than statistical abstractions. Characterizing an unknown failure as an “out-of-distribution latent state” provides no actionable signal for the permission loop to trigger a physical intervention. By contrast, stating an unmeasured surface friction coefficient, an undetected optical flare across a camera lens array, or an unobservable micro-fracture in an actuator housing identifies the exact physical deficit. Naming the missing observable establishes the boundary where learned inference stops and physical uncertainty begins.</p>
<p>The oil film gives the mobile manipulator its first entry. The premise is that every aisle floor supplies a friction coefficient of at least 0.204, the value its credible deceleration needs. The missing observable is the friction beneath a clear film, which the navigation camera and the lidar cannot tell from dry concrete. The stop from the aisle speed that fits the clear distance on a dry floor overruns it on the film, so a speed limit the entry imposes can hold only on floors whose friction is measured or controlled.</p>
<p>An open entry requires an <strong>operational response</strong>. For the aisles, the most the entry permits is a restricted mode of 1 m/s on floors under the site’s inspection regime. An inspected floor supports <span class="math inline">\(\mu \ge\)</span> 0.12, which gives a credible deceleration of 1.18 m/s² and a ceiling of 1.09 m/s, so the restricted mode sits below its ceiling.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> A route that the inspection regime does not cover is excluded, or the machine is withheld from it.</p>
<p>The restricted mode needs an owner able to keep its physical premises true. Site operations owns this entry through its spill procedure for pallet-jack routes, which sets the inspection interval and names the condition that withdraws permission. The signed speed limit on the permission path enforces the restriction, but a claim about friction cannot be maintained by a speed setting alone.</p>
<p>Every entry needs a <strong>closure test</strong> declared before collecting data. For the film, the test must qualify a new transducer, because no measurement by the camera or the lidar can exclude a clear film and more trials with them could not close the entry. The test is a floor-film detector whose miss rate is bounded at 0.1 percent by 2,995 failure-free trials on seeded films (<strong><a href="../07_evaluation/07_evaluation.html#sec-evaluation-trial-limits">Physical Trial Limits</a></strong>); until it passes, the restriction holds. A smaller campaign falls short. Zero misses in 1,000 independent trials bound the miss probability only at 0.002991 with 95 percent confidence. The detector must also report the film early enough that detection, permission, and braking together fit the clear distance, and the trial distribution, detection distance, latency, false alarms, and friction after detection must be declared in advance. A wheel-slip reflex can limit later motion but cannot establish friction before the wheels reach the film.</p>
<p>The same aisle carries a second entry. The stopping budget protects a static obstacle. A person who keeps walking toward the machine through the whole stop adds distance that the budget never charges (<strong><a href="../09_memory/09_memory.html#sec-memory-belief-through-occlusion">Belief Through Occlusion</a></strong>), and <strong><a href="../12_enforcement/12_enforcement.html#sec-enforcement-stopping-envelopes">Stopping Envelopes</a></strong> found that charging it would cap the base at this rack end far below its aisle speed. The premise is that no person approaches the rack end during a stop, and the missing observable is presence in the cross aisle the rack hides. The site’s crossing rule, a floor-marked crossing plus a rack-end presence sensor, is the restriction, and site operations owns it. The closure test qualifies the presence sensor by the same zero-failure sizing.</p>
<p>The pick station adds a third entry, and this one belongs to the arm. Its premise is that the object the arm grasps, and later hands to the coworker under <code>accept_item</code> (<strong><a href="../14_intervention/14_intervention.html#sec-intervention-human-authority">Human Authority Over Actuation</a></strong>), is the object the task names. <strong><a href="../10_intent/10_intent.html#sec-intent-request-to-proposal">From Request to Expiring Geometric Proposal</a></strong> showed how that premise fails. A thin-walled red glass jar beside the red mug on the takeaway conveyor draws a confident grounding, and the wrong target passes every geometric check the planner and the permission path apply. The missing observable is identity and fragility, which neither the wrist camera nor the grounding model can establish before contact.</p>
<p>The restriction on this entry has two parts. Site operations admits to the conveyor only items on the pick station’s declared item list, which holds no fragile look-alike, and the station admits a grasp only when the pick window holds exactly one object, so that a second object refuses the intent and sends the item to the coworker for a manual pick. Singulation makes the grounding unambiguous for the items it admits but supplies no identity information, and a mis-routed jar that arrives alone is contained only by the feed procedure. That residual is why the entry stays open. A grip-force ceiling set for the most fragile look-alike would need a crush limit for every item that might arrive, itself an unmeasured premise, so the register does not rest on one. Site operations owns the feed list and the singulation rule jointly with the task profile. The closure test is a qualified identity check at the station, a tag read or a scale-and-code check, whose false-accept rate is bounded at 0.1 percent with 95 percent confidence by the same 2,995 failure-free trials, run here on seeded look-alikes.</p>
<p><a href="#tbl-17-claims-register" class="quarto-xref">Table&nbsp;1</a> sets the three entries side by side. Each row carries the four components the register requires, so any entry can be audited without the prose around it.</p>
<div id="tbl-17-claims-register" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[22,24,26,28]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-17-claims-register-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: <strong>Residual-claims register for the aisle and the pick station</strong>: The three open premises behind the mobile manipulator’s aisle speed and its pick. For each, the register names the missing physical observable, the hazard it permits, the operating restriction and its accountable owner, and the predeclared closure test that would retire the restriction.
</figcaption>
<div aria-describedby="tbl-17-claims-register-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 24%">
<col style="width: 26%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Claim and missing state</th>
<th style="text-align: left;">Hazard mechanism</th>
<th style="text-align: left;">Active containment and owner</th>
<th style="text-align: left;">Predeclared closure test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Braking traction</strong>: every aisle floor supplies <span class="math inline">\(\mu \ge\)</span> 0.204; friction beneath a clear film is unobserved.</td>
<td style="text-align: left;">At <span class="math inline">\(\mu\)</span> = 0.05 the credible deceleration falls to 0.49 m/s², and the finished budget at 1.3 m/s grows to 2.95 m against a 1.10 m clear distance.</td>
<td style="text-align: left;">1 m/s on inspected floors (<span class="math inline">\(\mu \ge\)</span> 0.12, ceiling 1.09 m/s); uninspected routes excluded. <em>Owner</em>: site operations, through the spill procedure for pallet-jack routes.</td>
<td style="text-align: left;">A floor-film detector with a miss rate of at most 0.1% at 95% confidence, from 2,995 failure-free seeded-film trials, plus timing and clearance tests; the restriction holds until it passes.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Walking person</strong>: no person approaches the rack end during a stop; presence in the hidden cross aisle is unobserved.</td>
<td style="text-align: left;">A person walking at 1.6 m/s through the whole stop would cap the base far below its aisle speed at the rack end (<strong><a href="../12_enforcement/12_enforcement.html#sec-enforcement-stopping-envelopes">Stopping Envelopes</a></strong>).</td>
<td style="text-align: left;">The crossing rule, a floor-marked crossing plus a rack-end presence sensor. <em>Owner</em>: site operations.</td>
<td style="text-align: left;">Qualify the presence sensor by the same zero-failure sizing, 2,995 failure-free trials for a 0.1% miss bound.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Object identity</strong>: the object grasped is the object the task names; identity and fragility before contact are unobserved.</td>
<td style="text-align: left;">A confident grounding to a thin-walled glass jar beside the red mug passes every geometric check, and a grip the ceramic mug needs can crush the glass.</td>
<td style="text-align: left;">Feed control admits to the conveyor only items on the station’s declared list, none of them a fragile look-alike; singulation admits a grasp only with one object in the pick window. An off-list item arriving alone is contained only by the feed procedure. <em>Owner</em>: site operations, jointly with the task profile.</td>
<td style="text-align: left;">A qualified identity check at the station (tag read or scale-and-code) with a false-accept rate of at most 0.1% at 95% confidence, from 2,995 failure-free seeded look-alike trials; the restriction holds until it passes.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A release pipeline records each entry in a fixed schema, and its fields, units, and invariants appear with the other record layouts in <strong><a href="../backmatter/appendix_systems.html#sec-appendix-systems-wire-residual-claims">Residual-claims register</a></strong>.</p>
<p>All three entries close only through a qualified detector, a floor-film detector for the first, the rack-end presence sensor for the second, and an identity check at the station for the third. Each closure test therefore has to show that the qualified detector reports in time, the two aisle detectors early enough for the permission path to stop the machine and the identity check before the station admits the grasp, and that timing requirement has a physical limit of its own.</p>
</section>
<section id="sec-frontier-failures-without-detectors" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-frontier-failures-without-detectors">Failures Without Detectors</h2>
<p>A runtime detector is itself a physical subsystem. To operate as a <strong>practical detector</strong>, it must satisfy three coupled parameters: comprehensive coverage across the failure distribution, a bounded false-alarm rate, and a detection latency strictly shorter than the physical system’s time-to-harm. At the 1.3 m/s aisle speed, the finished stopping budget of <strong><a href="../12_enforcement/12_enforcement.html#tbl-enforcement-stopping-budget">The warehouse mobile manipulator's stopping budget</a></strong> leaves the mobile manipulator 102.6 mm of its clear distance unspent, which the machine covers in 78.9 ms (<strong><a href="../14_intervention/14_intervention.html#sec-intervention-authority-transitions">Authority Transitions</a></strong>). A detector for a person at the rack end that adds more than that to the observation path is not a detector for that hazard. The floor-film detector faces a stricter form of the same test. Its detection distance, less the travel during its own latency, must cover the dry-floor stop to the film’s edge, because a report that arrives once the wheels are on the film leaves a stop of 2.95 m against the 1.10 m clear distance. A detector that reports later is a post-incident logging mechanism. Producing an accurate classification label after crossing an irreversible threshold generates diagnostic evidence but cannot serve as a runtime safeguard.</p>
<p>The fundamental limit of runtime detection arises from observational indistinguishability. Consider two physical states of the world, <span class="math inline">\(S_A\)</span> and <span class="math inline">\(S_B\)</span>. In state <span class="math inline">\(S_A\)</span>, a commanded actuator trajectory <span class="math inline">\(u(t)\)</span> is safe. In state <span class="math inline">\(S_B\)</span>, the identical trajectory <span class="math inline">\(u(t)\)</span> causes structural damage or human injury, requiring the permission path to intervene and command a stop. The dynamics of the body impose a hard deadline <span class="math inline">\(t_{\text{deadline}}\)</span>, determined by actuator response time and system momentum, after which physical contact or mechanical yield cannot be prevented. If the telemetry history <span class="math inline">\(y(t)\)</span> provided by onboard instrumentation is identical for <span class="math inline">\(S_A\)</span> and <span class="math inline">\(S_B\)</span> across the entire interval <span class="math inline">\(t \le t_{\text{deadline}}\)</span>, no algorithm operating on those observations can reliably distinguish the benign state from the hazardous one. Identical traces rule out a state-specific response before that deadline. A conservative action chosen for both states or a passive mechanical limit may still protect them, if its own clearance and force assumptions are valid.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><a href="images/svg/margin_observational_indistinguishability_chain.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="images/svg/margin_observational_indistinguishability_chain.svg" class="img-fluid" style="width:100.0%" alt="Causal chain showing state split producing identical telemetry until deadline passes and irreversible damage occurs."></a></p>
<p><em>Identical pre-contact telemetry prevents software intervention before irreversible physical damage occurs.</em></p>
</div></div><div id="dfn-frontier-observational-indistinguishability" class="callout callout-definition" title="Observational indistinguishability">
<details class="callout-definition fbx-simplebox fbx-default" open=""><summary><strong>Definition 1.2: Observational indistinguishability</strong></summary><div>
<p><strong><em>Observational indistinguishability</em></strong> is the physical condition where two distinct world states, one nominal (<span class="math inline">\(S_A\)</span>) and one hazardous (<span class="math inline">\(S_B\)</span>), generate identical pre-harm sensor telemetry (<span class="math inline">\(y_A(t) \equiv y_B(t)\)</span>) up to the system’s physical action deadline (<span class="math inline">\(t_{\text{deadline}} = t_{\text{harm}} - t_{\text{act}}\)</span>).</p>
<ol type="1">
<li><strong>Significance</strong>: Without distinguishing physical energy prior to the action deadline, timely algorithmic differentiation is physically and mathematically impossible. Scaling neural model parameters, increasing dataset size, or accelerating inference compute cannot separate states that emit zero distinguishing physical energy before the time-to-harm.</li>
<li><strong>Distinction</strong>: Unlike epistemic uncertainty or high classifier entropy (which signals that the model knows it lacks evidence), observational indistinguishability often pairs with high output confidence and near-zero entropy because the neural network maps corrupted observations into nominal latent manifolds.</li>
<li><strong>Common pitfall</strong>: Relying on software anomaly detectors or VAE reconstruction loss to catch detectorless degradation. When sensor physics blinds the transducer, as piezoresistive crystal creep does, or the hazardous state lies outside the sensed path, as a weakened latch does for the joint channel, the anomaly detector consumes telemetry that carries no trace of the fault and fails silently.</li>
</ol>
</div></details>
</div>
<p>In a learned perception-action policy the same limit appears as shortcut learning. A vision-language-action (VLA) model <span class="citation" data-cites="brohan2023rt1 brohan2023rt2">(<a href="#ref-brohan2023rt1" role="doc-biblioref"><span class="nocase">Brohan, Brown, Carbajal, Chebotar, Dabis, et al.</span> 2023</a>; <a href="#ref-brohan2023rt2" role="doc-biblioref"><span class="nocase">Brohan, Brown, Carbajal, Chebotar, Chen, et al.</span> 2023</a>)</span> or an imitation policy <span class="citation" data-cites="zhao2023learning">(<a href="#ref-zhao2023learning" role="doc-biblioref">Zhao et al. 2023</a>)</span> minimizes its loss with whatever correlations the demonstrations contain, and where friction, material strength, or payload inertia goes unobserved, it can learn non-causal visual features, such as floor highlights or the angle of the lighting, as proxies for them. Under distribution shift those proxies fail, yet the encoder can still map the unfamiliar observation into the region of latent space it knows, so the policy acts with high confidence and little ensemble disagreement. An uncertainty estimate computed from that same latent representation, whether a Mahalanobis distance, a dropout variance, or a reconstruction residual, inherits the same blindness and cannot serve as an independent detector. The Brain cannot detect its own shortcut failure, which is why physical containment rests on the permission path below the proposal boundary rather than on the model’s self-assessment.</p>
<div class="no-row-height column-margin column-container"><div id="ref-brohan2023rt1" class="csl-entry" role="listitem">
<span class="nocase">Brohan, Anthony, Noah Brown, Justice Carbajal, Yevgen Chebotar, Joseph Dabis, Chelsea Finn, Keerthana Gopalakrishnan, et al.</span> 2023. <span>“<span>RT-1</span>: <span>Robotics Transformer</span> for Real-World Control at Scale.”</span> <em>Robotics: Science and Systems (RSS)</em>. https://doi.org/10.15607/RSS.2023.XIX.025.
</div><div id="ref-brohan2023rt2" class="csl-entry" role="listitem">
<span class="nocase">Brohan, Anthony, Noah Brown, Justice Carbajal, Yevgen Chebotar, Xi Chen, Krzysztof Choromanski, Tianli Ding, et al.</span> 2023. <span>“Rt-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control.”</span> <em>arXiv Preprint arXiv:2307.15818</em>.
</div><div id="ref-zhao2023learning" class="csl-entry" role="listitem">
Zhao, Tony Z., Vikash Kumar, Sergey Levine, and Chelsea Finn. 2023. <span>“Learning Fine-Grained Bimanual Manipulation with Low-Cost Hardware.”</span> <em>Robotics: Science and Systems (RSS)</em>. https://doi.org/10.15607/RSS.2023.XIX.016.
</div></div><p>Sensing hardware shows the same limit over longer durations. The flow regulator’s pressure transducer drifts as deposits build on its diaphragm, and a transducer whose zero has drifted low reports the same trend as a line that genuinely runs at the lower pressure. A single channel reports one scalar, and no algorithm on that signal can tell a changed process from a degraded calibration. Without an independent reference transducer or a proof test of the zero point, the drift is undetectable at runtime.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>The weakened latch at the door is the arm’s case of the same limit, and a faster one. Until the latch yields, the joint torque sensors read the same torques against a weakened latch as against a sound one, because both carry the same contact force, and the channel holds no trace of the strength that remains. The yield is irreversible, and no command issued after it restores the latch, so a faster classifier on the joint torque channel protects nothing. The defensible responses supply what that channel lacks. A proof test establishes the latch’s strength at a declared interval, and it covers the interval only if corrosion and wear cannot carry the yield force below the contact ceiling between two tests, a rate that the maintenance record, not the torque channel, must support. A passive compliant element in the wrist instead keeps the contact force below a declared floor on latch strength over a mechanically limited stroke, so the premise no longer depends on the latch’s state. <a href="#eq-frontier-passive-compliance" class="quarto-xref">Equation&nbsp;2</a> gives that element’s stiffness ceiling, with <span class="math inline">\(F_{\text{allow}}\)</span> set by the declared floor, which holds only if the element carries the entire contact load, the stroke cannot pass its stop, and wear and impact tests support the model.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> <span id="eq-frontier-passive-compliance"><span class="math display">\[k_{\text{spring}} \le \frac{F_{\text{allow}}-F_{\text{preload}}}{\Delta x_{\text{stall}}} \tag{2}\]</span></span></p>

<div class="no-row-height column-margin column-container"><div class="margin-pointer">
<p>↰ <strong>Prerequisite:</strong> Failures undetectable by sensory telemetry challenge the observation contracts formulated in <strong><a href="../08_perception/08_perception.html#sec-perception-observation-contract">The Observation Contract</a></strong>.</p>
</div></div><p>The Deepwater Horizon blowout failed in the opposite way from the Tempe collision of <strong><a href="../01_boundary/01_boundary.html#sec-boundary-when-fails">When the Boundary Fails</a></strong>, where the sensors had detected the pedestrian but a designed suppression withheld the braking that state warranted. In the blowout the protective device acted, but on a state that no sensor reported. A faster trigger or broader authority would not have changed the outcome, because no measurement separated the state the protection was qualified for from the actual one. A timelier response rule and a restored redundant brake path address a failure like Tempe’s. Only qualification and sensing extended to every state the protection may meet can repair the other kind, the detectorless failure this section describes and the one the oil film poses on the aisle.</p>
<div id="ws-frontier-deepwater-horizon-blind-shear-ram-structural" class="callout callout-war-story" title="Deepwater Horizon blind shear ram failure (2010)">
<p></p><details class="callout-war-story fbx-simplebox fbx-default" open=""><summary><strong>War Story 1.1: Deepwater Horizon blind shear ram failure (2010)</strong></summary><div><strong>Context</strong>: On April 20, 2010, the Macondo well in the Gulf of Mexico blew out beneath the <em>Deepwater Horizon</em> drilling rig. The last physical containment safeguard was the subsea blowout preventer (BOP), a stack of hydraulic valves and blind shear rams weighing approximately <span class="math inline">\(400\)</span> tons and anchored at the wellhead about <span class="math inline">\(1{,}500\text{ m}\)</span> below the surface <span class="citation" data-cites="csb2014macondo">(<a href="#ref-csb2014macondo" role="doc-biblioref">U.S. Chemical Safety and Hazard Investigation Board 2014</a>)</span>.<p></p>
<p><strong>Mechanism</strong>: The explosions likely activated the BOP’s automatic deadman system, which was meant to close the blind shear ram, shear the drill pipe, and seal the well. By then the drill pipe inside the BOP had buckled off center. The pressure difference between the inside and outside of the pipe had placed it in effective compression, a buckling mechanism that earlier investigations had not identified. The BOP was not designed to cut off-center pipe. The ram punctured and partially severed the pipe but could not close fully and seal the well.</p>
<p><strong>Impact</strong>: Flow through the punctured pipe resumed rapidly. Eleven crew members died, the rig sank about 36 hours after the explosions, and approximately 5 million barrels of oil spilled into the Gulf of Mexico <span class="citation" data-cites="csb2014macondo">(<a href="#ref-csb2014macondo" role="doc-biblioref">U.S. Chemical Safety and Hazard Investigation Board 2014</a>)</span>.</p>
<p><strong>Response</strong>: The <a href="https://www.csb.gov/csb-board-approves-final-report-finding-deepwater-horizon-blowout-preventer-failed-due-to-unrecognized-pipe-buckling-phenomenon-during-emergency-well-control-efforts-on-april-20-2010-leading-to-environmental-disaster-in-gulf-of-mexico/">U.S. Chemical Safety Board</a> recommended changes to blowout-preventer design, testing, and oversight. Its investigation also found two instances of miswiring and two backup-battery failures in the controls for the blind shear ram.</p>
<p><strong>Systems lesson</strong>: The pipe’s position inside the BOP was a state that no sensor reported, and the ram acted on it anyway (<span class="math inline">\(y_A(t) \equiv y_B(t)\)</span> for the centered and the buckled pipe). Its qualified cutting geometry did not cover the actual condition. Protection has to be qualified across every physical state it may meet, including pipe position, and across the independent control faults the CSB documented.</p>
</div></details>
</div>
<div class="no-row-height column-margin column-container"><div id="ref-csb2014macondo" class="csl-entry" role="listitem">
U.S. Chemical Safety and Hazard Investigation Board. 2014. <em>Investigation Report: Drilling Rig Explosion and Fire at the Macondo Well (Deepwater Horizon)</em>. Report No. 2010-10-I-OS. U.S. Chemical Safety Board.
</div></div><div class="no-row-height column-margin column-container"></div><p>When a failure mode lacks a practical detector, the remaining responses are to limit actuator authority under a validated force or clearance model, restrict the operating domain, add independent sensing, or schedule proof tests. A force limit rests on that validated model, because ISO 10218 and ISO/TS 15066 apply to their industrial robot scopes and supply no universal force limit for this machine. Active sensing is itself actuation. A small dither of the wheels, an active probe for the film, measures traction only where the wheels already are, so it cannot close the friction entry. Because the probe must not slip beyond the reserved clearance, the independent permission path must admit each probe command within a separately validated energy, contact, clearance, and timing envelope and choose a state-matched fallback when the needed bound is unavailable. If none of these measures can support the claim, operation must be withheld.</p>
<p>The safety case must document these gaps. <a href="#fig-17-epistemic-limits" class="quarto-xref">Figure&nbsp;1</a> marks where the argument runs out. The residual-claims register records the detector’s blind region, defining the set of physical states that produce indistinguishable observations, along with the maximum exposure duration permitted between physical proof tests. Treating an undetectable failure as a solved runtime problem undermines the validity of the safety case. Preserving the exact boundary where sensing stops forces the engineering organization to rely on physical constraints rather than software optimism.</p>
<div id="fig-17-epistemic-limits" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="t" data-fig-env="figure">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-17-epistemic-limits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/svg/fig17_epistemic_limits.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;1: Two limits on the claim: Panel (a) shows states with identical pre-deadline telemetry. A speed clamp is useful only with a supported braking and clearance envelope. Panel (b) shows the zero-event exposure required for a rare-rate claim under the chosen Poisson model; a barrier argument also needs observable state, a feasible control action, and valid timing assumptions."><img src="images/svg/fig17_epistemic_limits.svg" class="img-fluid figure-img" style="width:100.0%" alt="Panel (a) shows safe and hazardous states producing the same telemetry until after the action deadline, with a conditional speed clamp. Panel (b) shows zero-event exposure growing inversely with the target rate and a conditional barrier argument."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-17-epistemic-limits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: <strong>Two limits on the claim</strong>: Panel (a) shows states with identical pre-deadline telemetry. A speed clamp is useful only with a supported braking and clearance envelope. Panel (b) shows the zero-event exposure required for a rare-rate claim under the chosen Poisson model; a barrier argument also needs observable state, a feasible control action, and valid timing assumptions.
</figcaption>
</figure>
</div>
<p>Each detectorless mode still leaves a defensible response, and <a href="#tbl-17-detectorless-modes" class="quarto-xref">table&nbsp;2</a> sets four of them side by side.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<div id="tbl-17-detectorless-modes" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[23,26,24,27]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-17-detectorless-modes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: <strong>Detectorless physical failure taxonomy</strong>: Four failure modes, in transduction, contact, the drive, and learned perception, whose safe and hazardous states look identical to the existing channel before the time-to-harm. For each, the table gives why the channel misses it, the deadline or evidence it cannot meet, and the response that still supports a claim.
</figcaption>
<div aria-describedby="tbl-17-detectorless-modes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 26%">
<col style="width: 24%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Failure and missing state</th>
<th style="text-align: left;">Why the existing channel can miss it</th>
<th style="text-align: left;">Deadline or evidence deficit</th>
<th style="text-align: left;">Defensible response</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Pressure-sensor drift</strong>: zero offset changes with aging or deposition.</td>
<td style="text-align: left;">One channel cannot separate true pressure change from its own offset drift.</td>
<td style="text-align: left;">Drift may persist until the process reaches its pressure limit; a detector cannot be credited without a second reference.</td>
<td style="text-align: left;">Independent calibrated pressure channel, proof test, and rated relief path.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Latch-strength loss</strong>: corrosion or wear lowers the latch’s yield force below the contact ceiling.</td>
<td style="text-align: left;">Joint torque sensors read the same contact force against a weakened latch as against a sound one.</td>
<td style="text-align: left;">Latch strength is unmeasured between proof tests, and the yield is irreversible, so no later command restores the latch.</td>
<td style="text-align: left;">A passive compliant element sized by <a href="#eq-frontier-passive-compliance" class="quarto-xref">equation&nbsp;2</a> to a declared floor on latch strength, or proof tests of the latch.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Rotor flux loss</strong>: delivered torque differs from current-based estimate.</td>
<td style="text-align: left;">Stator current alone does not measure the torque constant after magnet damage.</td>
<td style="text-align: left;">A gravity-loaded axis may have little time to arrest once available torque is lost.</td>
<td style="text-align: left;">Measure torque or rotor state, derate within tested limits, and validate a holding or controlled-stop path.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Learned perception shift</strong>: an optical artifact is mistaken for a known scene.</td>
<td style="text-align: left;">Model confidence may remain high even while the physical scene differs.</td>
<td style="text-align: left;">Confidence or reconstruction loss alone does not bound clearance or stopping response.</td>
<td style="text-align: left;">Independent range/clearance checks and an admitted motion envelope, with residual blind regions recorded.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Every row fails the practical-detector test because the existing channel gives identical observations for the safe and hazardous states until the deadline has passed. Every defensible response supplies what that channel lacks: a second reference, a passive load limit, a direct torque measurement, or an independent range check. What that missing element is, and whether it can be built, decides the kind of gap each register entry records.</p>
</section>
<section id="sec-frontier-assumptions-change" class="level2">
<h2 class="anchored" data-anchor-id="sec-frontier-assumptions-change">What Would Change These Answers</h2>
<p>The three entries in the mobile manipulator’s residual-claims register lack the same element, a qualified detector for a state no sensor in service reports. Sorting every recorded gap by what is missing turns the register from a list of caveats into an engineering agenda, and a recorded gap falls into one of four classes, defined by the missing element. It stems from an <strong>unmeasured observable</strong> when the true physical state (such as a hidden internal defect) cannot be distinguished from sensor data before the deadline for action; from an <strong>evaluation deficit</strong> when the tail probability of failure cannot be bounded because these rare events require intractable physical exposure; from a <strong>theoretical deficit</strong> when the learned policy lacks a bounded relationship between training conditions and execution stability; or from a <strong>scope mismatch</strong> when the target claim exceeds what the system architecture can physically support. All three of the machine’s entries belong to the first class. More grounding-model trials at the pick station or more stopping runs on dry floors would treat them as evaluation deficits, which they are not. Naming the missing capability defines the exact physical or mathematical requirement that would discharge the entry.</p>
<p>Closing a gap from an unmeasured observable requires a new physical measurement that separates previously indistinguishable states within the permission path’s deadline. For the film, a software filter or a learned estimator running on the navigation camera and the lidar cannot be that measurement, because it consumes the same observations that already fail to separate film from dry floor. The floor-film detector must respond to the film through an independent physical channel, and it closes the entry only if it meets the timing requirement of <a href="#sec-frontier-failures-without-detectors" class="quarto-xref">section&nbsp;1.4</a>, holds a bounded false-alarm rate, and fails independently of the cameras.</p>
<p>Closing an evaluation deficit requires replacing raw sample counts with estimators whose bias and variance can be bounded analytically. Logging more unperturbed operation, or running simulated episodes whose fidelity in the tail is unverified, cannot bound a tail rate. An importance-sampling or adaptive stress-testing scheme can, if it demonstrates conservative estimates on benchmark distributions whose answer is known and reports effective independent exposure rather than raw trial counts. Ten thousand simulated trajectories that explore one basin of a collision surface say little about the others, so effective sample size must be estimated from the weights and their dependence (for high-quantile tail bounds and extreme value modeling, see <strong><a href="../backmatter/appendix_ml.html#sec-appendix-ml-evt">Extreme Value Theory and Tail Risk</a></strong>).</p>
<p>Closing a theoretical deficit requires a bounded analytical claim paired with a runtime mechanism that checks its premises. For a policy trained by imitation or reinforcement learning, the deficit is the absence of any guarantee of bounded outputs under distribution shift, and neither asymptotic convergence nor a bound resting on an uncheckable Lipschitz constant closes it. The theory must state the invariance it guarantees and the support over which it holds, and the machine must carry a monitor that flags when its state leaves that support, with bounded estimator error and decision delay and a validated state-matched stop.</p>
<p>To prevent research optimism from corrupting the safety case, each candidate advance must undergo evaluation against a predeclared closure test. The test defines the missing argument link, the numerical threshold required for sufficiency, and the independent evidence necessary to verify it. An advance fails the test if it merely relocates an assumption to a less visible layer of the system. Replacing a neural network controller with a control-barrier function whose certificate assumes perfectly known linear dynamics does not close a theoretical deficit. It merely relocates the unmodeled dynamics from the opaque network weights to the barrier derivative. A candidate advance is stopped before it can alter the safety verdict whenever its validation relies on the exact unverified properties it was designed to establish.</p>
<p>Research directions in physical machine learning must be judged solely by whether they convert an open residual claim into verified evidence capable of altering the operational verdict. General improvements on benchmark leaderboards, such as a 3 percent reduction in average tracking error or higher reward on a standard task suite, provide no evidence toward closing an unsupported safety link. A research project becomes relevant to physical deployment only when its deliverable targets a specific entry in the claims register, whether by providing the missing transducer, bounding the tail estimator, or furnishing the runtime-checked stability proof. If an advance improves mean performance but leaves the detector blind spot or the tail uncertainty unchanged, the authority limits of the machine remain exactly where they were.</p>
<p>Certain gaps cannot be closed by any known sensor, sampling regime, or mathematical framework. When physical laws, computational limits, or economic constraints preclude the necessary measurement or proof, the safety case cannot remain suspended in anticipation of future discovery. Narrowing the actuator’s physical authority, restricting the operational design domain (ODD), or refusing to operate the machine is not an admission of research defeat. It is the engineering resolution. Classical fault-tolerant design reached the same conclusion, that dependable operation comes from self-monitoring thresholds and structural isolation that contain faults rather than from eliminating every disturbance. An arm whose compliant wrist bounds contact force below a declared floor on latch strength does not need to detect a weakened latch to leave it intact. The residual-claims register records the boundary of verifiable knowledge, and the permission path and the machine’s passive limits enforce the constraints that bound the consequence of what remains unknown.</p>
<p>The register, the practical-detector test, and the four gap classes have so far been applied to machines whose records already existed. The method must also hold for a machine with no records yet, where the engineer has to decide which premises to measure, which to restrict, and which to leave open.</p>
</section>
<section id="sec-frontier-generalizing-unfamiliar-systems" class="level2">
<h2 class="anchored" data-anchor-id="sec-frontier-generalizing-unfamiliar-systems">Generalizing to Unfamiliar Systems</h2>
<p>Applied in order to a machine not previously examined, the four laws of <strong><a href="../01_boundary/01_boundary.html#sec-boundary-bedrock-laws">The Four Bedrock Laws</a></strong> isolate its hazards before its hardware is energized. Consider an automated packaging cell designed for prepared meals. The machine moves rigid plastic trays along a linear track, presses a heated sealing head onto tray perimeters to bond plastic barrier film, and injects pressurized steam into product cavities to blanch ingredients immediately prior to sealing. This cell couples all three machine classes of <strong><a href="../01_boundary/01_boundary.html#sec-boundary-four-archetypes">Three Machine Classes</a></strong> within a single enclosure, the tray as moving mass, the sealing head as contact force, and the steam as thermal flow.</p>
<p>The first law asks what the cell cannot undo, so the evaluation begins by cataloging the irreversible state changes the cell can produce and the physical bounds that govern them. A loaded food tray traversing a linear transfer rail carries momentum. When a tray strikes an obstruction, the kinetic energy is dissipated through plastic deformation of the container and structural deflection of the frame, a state transition that cannot be reversed by commanding the drive motor in reverse. The sealing mechanism introduces a second irreversible boundary. An actuator drives an aluminum sealing head at <span class="math inline">\(180^\circ\text{C}\)</span> against the tray flange to melt polymer bonding layers. If the actuator exerts force beyond the compressive yield strength of the container wall, the flange buckles, destroying the hermetic geometry. The steam subsystem introduces a third irreversible boundary through enthalpy exchange. Steam supplied at <span class="math inline">\(120^\circ\text{C}\)</span> delivers heat to the product; the product-zone temperature can remain lower only under a measured heat-transfer and dwell model. Once proteins denature and cell walls rupture under excessive thermal exposure, cooling the chamber cannot restore product texture.</p>
<p>Because the tray’s momentum is already committed, the permission path must act before the carriage consumes its clearance. Consider, with illustrative values throughout, a linear carriage of mass <span class="math inline">\(m_{\text{carriage}} = 12.0\text{ kg}\)</span> transporting a loaded tray at a nominal velocity of <span class="math inline">\(v_{\text{nom}} = 1.50\text{ m/s}\)</span> toward an optical inspection station whose mechanical gate provides a physical clearance margin of <span class="math inline">\(D_{\text{clear}} = 60.0\text{ mm}\)</span> before contacting a rigid frame stop. An overhead vision system detects a closing inspection gate. The controller commands an electromagnetic track brake with a credible deceleration of <span class="math inline">\(a_{\text{brake}} = 15.0\text{ m/s}^2\)</span>, a value that assumes the pad and rail friction stay as tested. Determining whether an onboard vision system can halt the carriage prior to an impact requires computing the pre-brake delay <span class="math inline">\(\tau_{\text{delay}}\)</span> across the full observation-to-braking path: optical exposure and rolling-shutter integration (<span class="math inline">\(t_{\text{exp}} = 16.0\text{ ms}\)</span>), direct memory access (DMA) transfer and neural detection inference (<span class="math inline">\(t_{\text{inf}} = 36.0\text{ ms}\)</span>), CAN-FD safety arbitration bus latency (<span class="math inline">\(t_{\text{bus}} = 2.0\text{ ms}\)</span>), and brake solenoid flux buildup rise time (<span class="math inline">\(t_{\text{sol}} = 10.0\text{ ms}\)</span>), summing to <span class="math inline">\(\tau_{\text{delay}} = 16.0 + 36.0 + 2.0 + 10.0 = 64.0\text{ ms} = 0.064\text{ s}\)</span>.</p>
<p>Over this delay, the carriage travels blind for <span class="math inline">\(d_{\text{blind}} = v_{\text{nom}} \tau_{\text{delay}} = 1.50\text{ m/s} \times 0.064\text{ s} = 96.0\text{ mm}\)</span>, which alone exceeds the <span class="math inline">\(60.0\text{ mm}\)</span> clearance, so the physical deadline is missed before braking begins. Once the solenoid builds flux and mechanical pads engage, deceleration consumes an additional distance <span class="math inline">\(d_{\text{brake}} = \frac{v_{\text{nom}}^2}{2 a_{\text{brake}}} = \frac{(1.50\text{ m/s})^2}{2 \times 15.0\text{ m/s}^2} = 75.0\text{ mm}\)</span>. The stopping distance of <strong><a href="../02_body/02_body.html#sec-body-kinetic-momentum">Kinetic Momentum</a></strong> is the sum of the two, blind travel that grows linearly with speed and braking distance that grows with its square, so <span class="math inline">\(d_{\text{stop}} = d_{\text{blind}} + d_{\text{brake}} = 96.0\text{ mm} + 75.0\text{ mm} = 171.0\text{ mm}\)</span>. That stop exceeds the physical clearance by a deficit of <span class="math inline">\(\Delta d = d_{\text{stop}} - D_{\text{clear}} = 111.0\text{ mm}\)</span>, and the machine cannot stop before the modeled gate at this velocity by relying on that vision path.</p>
<p>The second law asks what the cell’s learned proposers have shown they can do. Three of them propose actions here, one in each domain. A vision model infers tray contents to propose carriage transit speeds, a multimodal network estimates packaging film thickness to propose sealing forces and dwell durations, and a thermal estimator proposes steam valve pulse widths from incoming product temperature. Each proposer’s actions choose part of what it observes next (<strong><a href="../05_data/05_data.html#sec-data-endogenous-experience">Endogenous Experience</a></strong>). A slower carriage changes the motion blur and timing of the frames the vision model sees, a longer dwell changes the film that the next thickness estimate reads, and a steam pulse changes the product temperature the thermal estimator receives. Their competence therefore extends only to the states a closed-loop evaluation covered, and the question for this cell is whether the target ODD of its evaluation record (<strong><a href="../07_evaluation/07_evaluation.html#sec-evaluation-logs">Evaluation Logs</a></strong>) contains the states that operation will admit. A restriction imposed after training is itself a change of operating condition. If the demonstrations were collected at the nominal transit speed, the derated mode that the cell’s release claim requires moves the vision model into conditions its evaluation never sampled, so the restriction that shortens the stop also opens a regime without evidence. Either the evaluation samples the restricted mode before release, or the release claim records that regime as an open premise.</p>
<p>The third law places those proposals beneath an authority split that the proposers cannot delay or corrupt. The permission path keeps the proposals from reaching actuators directly. Its independent kinematic check, at <span class="math inline">\(1\text{ kHz}\)</span>, monitors optical encoders along the track, admitting carriage velocity only where rangefinder coverage, measured gate clearance, and a validated stop path support the envelope. For the sealing head, a mechanical force limiter caps transmitted force at a selected <span class="math inline">\(220\text{ N}\)</span>, a cap that holds only while the limiter’s calibration does. For the steam delivery system, an independent temperature path closes the steam valve when a sensed product-zone temperature reaches <span class="math inline">\(105^\circ\text{C}\)</span> or dwell reaches <span class="math inline">\(400\text{ ms}\)</span>. The learned policy retains authority to optimize throughput and seal quality within these bounds, but the permission path retains sole authority to permit physical execution.</p>
<p>The fourth law turns what the evidence supports into a release claim and names what it leaves open. The evidence record can support a restricted kinetic claim after tests of rangefinder coverage, gate clearance, and braking. The firmware velocity clamp is sized from the same stopping distance. Requiring the stop to fit within the physical clearance with a safety margin of <span class="math inline">\(d_{\text{margin}} \ge 15.0\text{ mm}\)</span> imposes the constraint <span class="math inline">\(d_{\text{stop}}(v) \le 45.0\text{ mm}\)</span>. Reducing operational velocity shortens both terms, and derating it threefold, from <span class="math inline">\(v_{\text{nom}} = 1.50\text{ m/s}\)</span> to a firmware clamp of <span class="math inline">\(v_{\text{clamp}} \le 0.50\text{ m/s}\)</span>, compresses blind travel linearly from <span class="math inline">\(96.0\text{ mm}\)</span> to <span class="math inline">\(d_{\text{blind}} = 0.50\text{ m/s} \times 0.064\text{ s} = 32.0\text{ mm}\)</span>, while braking distance falls ninefold from <span class="math inline">\(75.0\text{ mm}\)</span> down to <span class="math inline">\(d_{\text{brake}} = \frac{(0.50\text{ m/s})^2}{2 \times 15.0\text{ m/s}^2} \approx 8.3\text{ mm}\)</span>. The composite stop <span class="math inline">\(d_{\text{stop}} = 40.3\text{ mm}\)</span> fits within the <span class="math inline">\(45.0\text{ mm}\)</span> threshold, preserving a <span class="math inline">\(19.7\text{ mm}\)</span> physical margin. Simultaneously, carriage kinetic energy (<span class="math inline">\(E_k = \frac{1}{2} m v^2\)</span>) drops quadratically by 88.9 percent, from <span class="math inline">\(13.5\text{ J}\)</span> to <span class="math inline">\(1.50\text{ J}\)</span>.</p>
<p>Assembling the evidence record also uncovers claims that remain unsupported. To assess seal hermeticity, the engineering team evaluates a vision model that inspects optical scattering through the steam chamber for micro-tears in the sealing film. Within the chamber, localized steam condensation creates optical refraction patterns that mimic film defects while masking genuine punctures. Because no independent physical sensor exists in the cell to measure film seal integrity in real time under dense vapor, this claim has no practical detector. Marking this link as detectorless and unsupported in the claims register is not an omission in the documentation, but an accurate statement of what the evidence can justify.</p>
<p>The derated stop therefore supports a <em>candidate restricted mode</em> for transport at <span class="math inline">\(0.50\text{ m/s}\)</span>, provided the stated 64 ms end-to-end delay, <span class="math inline">\(15\text{ m/s}^2\)</span> credible deceleration, and <span class="math inline">\(60\text{ mm}\)</span> clearance are validated together. Sealing and thermal processing remain conditional on tests of the force limiter, cutoff, material limits, and independent fault path. Autonomous package sign-off is refused because vapor can conceal film defects from the available vision sensor and the example has not established seal integrity independently. That link could be closed by post-cooling leak or vacuum-decay inspection, a tested material-process argument, a self-indicating film, or mandatory downstream inspection. A throughput model cannot replace that physical evidence.</p>
<p>The evaluation of the cell did not begin with model architecture, training losses, or benchmark scores. It began at the physical body, where mass, force, and energy create irreversible state changes, and it ended with an evidence record that marks its open links and restricts authority to what the evidence supports. A neural network predicting a high probability of a safe stop will still crash if the brakes cannot engage before the clearance is consumed.</p>
</section>
<section id="sec-frontier-architectural-synthesis" class="level2">
<h2 class="anchored" data-anchor-id="sec-frontier-architectural-synthesis">What the Four Laws Leave Open</h2>
<p>The running machine ends the book refused. On the book’s evidence the adjudicator of <strong><a href="../16_release/16_release.html#sec-release-case-worked-full">A Case Worked in Full</a></strong> signs <code>REFUSE</code> on all six claims, because each rests on a premise the records leave illustrative or unknown. The measurements of <strong><a href="../16_release/16_release.html#tbl-16-cond-measurements">Measurements that would move the verdict toward `COND`</a></strong> would move that verdict only part of the way. Once they support the premises they settle, the most a release could sign is <code>COND</code> for a named part of the envelope, covering aisle travel in the 1 m/s restricted mode on inspected floors, the door at the guarded approach, and the handover to the coworker. The 1.3 m/s normal mode would stay unsigned, because it rests on the friction floor that the oil film leaves open. Under either verdict the three entries of <a href="#tbl-17-claims-register" class="quarto-xref">table&nbsp;1</a> stay open, each with its owner and closure test, and all three are unmeasured observables that only a qualified detector can close: a floor-film detector, a qualified rack-end presence sensor, and a qualified identity check at the pick station. None of them is a scope mismatch or a theoretical deficit. The machine’s authority stops where the register says it does.</p>
<p>That verdict is the four laws applied to one machine, and the packaging cell carried the same laws through a machine the book had not examined. Each law also led one part of this book, and each part handed forward records that state their own conditions. Together those records carry the answer to the question the book opened with, and they also mark where that answer stops. <a href="#fig-17-causal-loop-synthesis" class="quarto-xref">Figure&nbsp;2</a> draws the loop they protect. The Brain proposes, the permission path admits or refuses each proposal against fresh state, and the Body delivers the admitted command across the Boundary into a World that keeps evolving whether or not any level observes it.</p>
<div id="fig-17-causal-loop-synthesis" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="t" data-fig-env="figure">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-17-causal-loop-synthesis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/svg/fig17_closed_loop_synthesis.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;2: Closed causal loop: The Brain proposes across the proposal boundary, and the permission path in the Nervous System admits, modifies, or refuses each proposal before the Body acts. The Body’s current becomes force and motion at the Boundary, the World evolves, and the Boundary returns measurements with capture times to the permission path and the Brain. Not every state of the World reaches a sensor. The governance envelope surrounds all five levels and changes on the timescale of releases rather than control cycles. The 1 kHz permission loop is one implementation, not a universal rate."><img src="images/svg/fig17_closed_loop_synthesis.svg" class="img-fluid figure-img" style="width:100.0%" alt="Five stacked levels inside a dashed governance envelope: Brain, Nervous System, Body, Boundary, and World, with a dashed proposal boundary between the Brain and the Nervous System. Arrows run down from the Brain to the World, labeled proposal, admitted command, current in a winding, and force and motion. A return arrow runs from the World to the Boundary, then up a side lane to the Nervous System, labeled fresh state, and to the Brain, labeled observations. Labels give the intent model 1 to 5 Hz, the chunk policy 10 to 50 Hz, perception at sensor rate, a 1 kHz permission loop in one implementation, and a 10 to 25 kHz current loop; the Boundary is event-timed, the World is continuous, and governance has no control rate."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-17-causal-loop-synthesis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: <strong>Closed causal loop</strong>: The Brain proposes across the proposal boundary, and the permission path in the Nervous System admits, modifies, or refuses each proposal before the Body acts. The Body’s current becomes force and motion at the Boundary, the World evolves, and the Boundary returns measurements with capture times to the permission path and the Brain. Not every state of the World reaches a sensor. The governance envelope surrounds all five levels and changes on the timescale of releases rather than control cycles. The 1 kHz permission loop is one implementation, not a universal rate.
</figcaption>
</figure>
</div>
<p><a href="#tbl-17-master-synthesis" class="quarto-xref">Table&nbsp;3</a> pairs each law with the records that carry it, the premise its evidence cannot always settle, and the restriction that holds while that premise stays open. The numbers each row needs come from the particular machine and its limit records, not from the table.</p>
<div id="tbl-17-master-synthesis" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[14,17,25,22,22]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-17-master-synthesis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: <strong>The four laws and what they leave open</strong>: Each law leads one part of the book and is carried by that part’s records. The last two columns name the premise its evidence cannot always settle and the restriction that holds while the premise is open, for a particular machine rather than as a universal hardware floor.
</figcaption>
<div aria-describedby="tbl-17-master-synthesis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 25%">
<col style="width: 22%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Law</th>
<th style="text-align: left;">Part</th>
<th style="text-align: left;">Records that carry it</th>
<th style="text-align: left;">Premise the evidence cannot always settle</th>
<th style="text-align: left;">What restricts operation while it is open</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Irreversibility</strong></td>
<td style="text-align: left;">I (<strong><a href="../02_body/02_body.html#sec-body">The Physical Body</a></strong>, <strong><a href="../03_brain/03_brain.html#sec-brain">The Cognitive Brain</a></strong>, <strong><a href="../04_nervous/04_nervous.html#sec-nervous">The Nervous System</a></strong>)</td>
<td style="text-align: left;">Limit records (<strong><a href="../02_body/02_body.html#sec-body">The Physical Body</a></strong>); the proposer’s limits (<strong><a href="../03_brain/03_brain.html#sec-brain">The Cognitive Brain</a></strong>), which enter the handoff record (<strong><a href="../04_nervous/04_nervous.html#sec-nervous">The Nervous System</a></strong>)</td>
<td style="text-align: left;">Each measured limit, such as floor friction, payload, brake onset, or observation age, still holds under present conditions</td>
<td style="text-align: left;">A speed or force ceiling sized from the credible limit, a lease derived from the stopping budget, and a fallback reachable from the current state</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Endogenous data</strong></td>
<td style="text-align: left;">II (<strong><a href="../05_data/05_data.html#sec-data">Physical Data</a></strong>, <strong><a href="../06_training/06_training.html#sec-training">Policy Training</a></strong>, <strong><a href="../07_evaluation/07_evaluation.html#sec-evaluation">Closed-Loop Evaluation</a></strong>)</td>
<td style="text-align: left;">Demonstration provenance record, policy manifest, evaluation record</td>
<td style="text-align: left;">The states the machine enters lie inside the target ODD that closed-loop evaluation sampled</td>
<td style="text-align: left;">Operation confined to the target ODD, with a runtime monitor on every boundary that can be monitored</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Proposal is not permission</strong></td>
<td style="text-align: left;">III (<strong><a href="../08_perception/08_perception.html#sec-perception">Sensor Perception</a></strong>, <strong><a href="../09_memory/09_memory.html#sec-memory">Spatial Memory</a></strong>, <strong><a href="../10_intent/10_intent.html#sec-intent">Grounded Intent</a></strong>, <strong><a href="../11_planning/11_planning.html#sec-planning">Trajectory Planning</a></strong>, <strong><a href="../12_enforcement/12_enforcement.html#sec-enforcement">Safety Enforcement</a></strong>, <strong><a href="../13_placement/13_placement.html#sec-placement">Silicon Placement</a></strong>)</td>
<td style="text-align: left;">Observation contract, belief record, intent lease, trajectory record, enforcement record, placement record</td>
<td style="text-align: left;">The permission path sees fresh, distinguishable state and meets its deadline under load</td>
<td style="text-align: left;">Refusal and the fallback ladder; an expired lease or stale evidence removes permission without waiting for the proposer</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Evidence bounds authority</strong></td>
<td style="text-align: left;">IV (<strong><a href="../14_intervention/14_intervention.html#sec-intervention">Supervisory Intervention</a></strong>, <strong><a href="../15_verification/15_verification.html#sec-verification">Adversarial Verification</a></strong>, <strong><a href="../16_release/16_release.html#sec-release">Deployment Release</a></strong>)</td>
<td style="text-align: left;">Authority record, fault record, release manifest, and the residual-claims register of this chapter</td>
<td style="text-align: left;">The premises of the release claim still hold after release</td>
<td style="text-align: left;">A conditional verdict with standing conditions, and a register entry that restricts authority until its closure test passes</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Four decisions keep the restrictions in the table’s last column operational. First, preserve each open entry across model updates until a predeclared closure test supplies evidence. Second, keep learned outputs as proposals and maintain an independently validated permission and fallback path whose processor, scheduling period, sensor coverage, and actuator response follow the plant’s measured deadlines. Third, use passive limits only where their load path, stroke, wear, and stopping consequences are tested. Fourth, require named engineering and operations owners to sign the release conditions and define the measurements that withdraw authority. Down that column, every law ends the same way, in a restriction that holds until evidence lifts it rather than a guarantee that holds regardless of the evidence.</p>
</section>
<section id="sec-frontier-fallacies-pitfalls" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-frontier-fallacies-pitfalls">Fallacies and Pitfalls</h2>
<p>Some hazards are unobservable through available sensors, and some claims require more exposure than the design can accumulate. Both limits must shape operating authority rather than disappear into a confidence score.</p>

<div class="no-row-height column-margin column-container"><div class="margin-pointer">
<p>↰ <strong>Prerequisite:</strong> The gap between verified models and unmodeled friction challenges the safety cases in <strong><a href="../16_release/16_release.html#sec-release-safety-cases-claims">Safety Cases and Claims</a></strong>.</p>
</div></div><div class="fallacy-pitfall">
<p><strong>Pitfall</strong>: <em>Relying on vision-based perception alone when the physical hazard is observationally indistinguishable.</em></p>
<p>The mobile manipulator approaches a transparent hydraulic-fluid film that its navigation camera and lidar cannot distinguish from dry concrete, producing observational indistinguishability. When the wheels enter the film and spin without grip, the slip reveals the changed surface only after the deceleration the stop assumed is gone. A visually clear path says nothing about the friction the admitted speed requires. The operating envelope must account for that unobserved condition through defensible speed restrictions or independently validated sensing. The residual-claims register must retain the friction assumption and its containment measure instead of treating missing visual evidence as evidence of traction.</p>
</div>
<div class="fallacy-pitfall">
<p><strong>Fallacy</strong>: <em>Stator temperature and current measurements are sufficient to detect rotor magnet flux degradation.</em></p>
<p>The rotor-flux row of <a href="#tbl-17-detectorless-modes" class="quarto-xref">table&nbsp;2</a> already names this gap. Torque follows <span class="math inline">\(\tau = K_t I\)</span> (<strong><a href="../02_body/02_body.html#sec-body">The Physical Body</a></strong>), so when magnet damage lowers <span class="math inline">\(K_t\)</span>, the drive still reports its commanded current and the expected Joule heating while the joint delivers less torque than that current implies. Nominal current is not proof of torque authority, so qualification must verify torque capability independently and the holding path must not assume the original torque.</p>
</div>
<div class="fallacy-pitfall">
<p><strong>Fallacy</strong>: <em>Massive cloud simulation can substitute for physical exposure in certifying open-world safety.</em></p>
<p>A team runs billions of simulated hours in the cloud to bypass the cost of physical exposure. Simulation evidence holds only for the simulator’s own model (<strong><a href="../07_evaluation/07_evaluation.html#sec-evaluation-evidence-regimes">Evidence Regimes</a></strong>), and a simulated floor with the friction of inspected concrete says nothing about a clear film (<strong><a href="../07_evaluation/07_evaluation.html#sec-evaluation-limits">What Evaluation Cannot Establish</a></strong>). Repetition inside that closed model adds no evidence about the physics it omits, so it cannot validate sim-to-real fidelity against the deployment conditions. Simulation remains useful for logic checks and regressions, while physical safety claims also require measurements or validated operating envelopes for the machine. The release case must distinguish simulated evidence from evidence that its assumptions hold on the physical system.</p>
</div>
</section>
<section id="sec-frontier-summary" class="level2">
<h2 class="anchored" data-anchor-id="sec-frontier-summary">Summary</h2>
<p>At the causal boundary (<strong><a href="../01_boundary/01_boundary.html#sec-boundary-causal-boundary">The Causal Boundary</a></strong>), a computational decision becomes part of a continuing, irreversible physical process. The architecture developed throughout this book connects this physical irreversibility to measured budgets, explicit interfaces, independent enforcement, and accountable release decisions. Its frontier lies in the premises those mechanisms still depend on but cannot fully observe or verify. On the running machine, the arithmetic of the stopping budget never changed when the oil film appeared, but one of its terms had rested all along on a floor that nothing measured, and irreversibility made that unmeasured term as binding as any measured one. An engineering record must expose such limits and let them restrict operation for as long as the machine runs, not only on the day a release is signed. Engineering embodied intelligence requires knowing when the available evidence is sufficient to act and when it is not.</p>
<div id="callout-takeaways*-1.2" class="callout callout-takeaways" title="The epistemic frontier and what the laws leave open">
<details class="callout-takeaways fbx-simplebox fbx-default" open=""><summary><strong>Key Takeaways: The epistemic frontier and what the laws leave open</strong></summary><div>
<ul>
<li><strong>An open premise restricts authority:</strong> The residual-claims register takes each premise the release manifest left open and gives it a missing observable, a restriction, an owner, and a closure test declared in advance. On the aisle, the friction entry caps any release at its restricted mode on inspected floors until a floor-film detector passes that test.</li>
<li><strong>A late detector is only a logger:</strong> A detector protects against a hazard only if its latency fits inside the margin the stop leaves unspent. When safe and hazardous states give identical telemetry until the action deadline, no algorithm separates them in time, and passive compliance, a restricted envelope, or a second physical channel must carry the claim.</li>
<li><strong>Trials cannot reach a rare-hazard rate:</strong> The exposure wall of <strong><a href="../07_evaluation/07_evaluation.html#sec-evaluation-trial-limits">Physical Trial Limits</a></strong> puts a rare-hazard rate beyond any practical failure-free campaign. A shield between proposal and actuation earns credit only for hazard classes it can observe and intercept in time, and its proposal rate, coverage, and common-cause terms each need evidence of their own.</li>
<li><strong>Research counts when it closes an entry:</strong> A new sensor, estimator, or proof matters for deployment only when it closes a named register entry by supplying the missing observable, bounding the tail, or checking its own premises at runtime. An entry that nothing can close is resolved by narrowing authority or withholding operation, not by waiting.</li>
<li><strong>Every law leaves a premise open:</strong> Irreversibility rests on measured limits that still hold; endogenous data, on a target ODD that covers the states the machine enters; proposal is not permission, on fresh and distinguishable state; and evidence bounds authority, on premises that still hold after release. Authority stops where that evidence does.</li>
</ul>
</div></details>
</div>
<div id="callout-chapter-connection*-1.3" class="callout callout-chapter-connection" title="From physical AI to the systems discipline">
<p></p><details class="callout-chapter-connection fbx-simplebox fbx-default" open=""><summary><strong>What’s Next: From physical AI to the systems discipline</strong></summary><div>This book completes an investigation into the full architecture of machine learning systems. Across the systems curriculum, we explored the single machine (mastering the silicon contract, arithmetic intensity, memory hierarchies, and local hardware acceleration), distributed fleets (navigating collective communication fabrics, fault tolerance, cluster orchestration, and high-throughput serving infrastructure), and agentic software trajectories (constructing sandboxed execution environments, dynamic context working sets, and deterministic verification harnesses for autonomous multi-step reasoning). Here, machine learning leaves the digital domain to inhabit embodied physical intelligence—where learned foundation models act as unprivileged proposal engines, real-time nervous systems enforce validated operating bounds, and artificial intelligence at last meets the unyielding conservation laws of the physical universe. This work is dedicated to the students, researchers, and systems engineers who take up the challenge of giving machines safe and capable hands in an open physical world.<p></p>
</div></details>
</div>
<p><em>Prof.&nbsp;Vijay Janapa Reddi, Harvard University</em></p>



</section>
</section>


<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p><strong>Popperian Falsification</strong>: Karl Popper formalized the asymmetry of empirical induction: no finite sequence of safe observations can prove universal safety, whereas a single counterexample refutes it. Operational fleet hours establish survival rates strictly under observed stationary conditions, not out-of-distribution guarantees. Extrapolating zero observed incidents to unbounded environments produces an illusory sense of safety that fails upon encountering unmodeled edge cases.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><strong>Evidence Across Updates</strong>: An updated model may alter the proposal distribution. Earlier data can be pooled only with a justified configuration-equivalence and exposure argument; an update does not automatically erase every observation. The exposure wall’s constant-rate model also requires a defensible treatment of shared fleet conditions and correlated faults.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><strong>Velocity Kinetic Derating</strong>: <span class="math inline">\(E_k=mv^2/2\)</span> decreases quadratically with speed. Stopping distance still depends on a validated credible deceleration and total response delay; a speed register alone cannot compensate for arbitrarily low friction.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><strong>Piezoresistive Transducer Drift</strong>: Mechanical stress relaxation, surface oxidation, and temperature cycles alter the piezoresistive coefficient of silicon strain gauges over extended campaigns. Monolithic software filters cannot separate slow baseline voltage drift from true process pressure increments, creating an unobservable state transition. Preventing overpressure therefore requires independent physical zero-point proof-tests or dual-dissimilar sensing architectures.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><strong>Contact Boundary</strong>: Rigid impact and friction transitions can invalidate a smooth free-motion model. Peak contact force and component damage require measured stiffness, damping, geometry, and actuator response; neither a controller nor a passive part alone supplies a universal bound.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p><strong>Motor Thermal State</strong>: Winding resistance and magnet flux can change with temperature. Whether that changes braking authority depends on the drive, current limits, load, and measured thermal model; a separate holding path may be required for gravity-loaded axes.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mlsysbook\.ai\/vol4\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../16_release/16_release.html" class="pagination-link" aria-label="Deployment Release">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Deployment Release</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2024-2026 Harvard University. Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC-BY-NC-SA 4.0</a><br> <!-- MLSB_BUILD_STAMP --></p>
</div>   
    <div class="nav-footer-center">
<p><a href="../vol3/">← Volume III: Agentic (Draft)</a></p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 <span class="release-pill" data-release-pill=""></span>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/harvard-edge/cs249r_book">
      <i class="bi bi-github" role="img" aria-label="View source on GitHub">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/harvard-edge/cs249r_book">
      <i class="bi bi-star" role="img" aria-label="Star this repository">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
    <script type="text/javascript">
    (function(d) {
      function renderPseudocode() {
        d.querySelectorAll(".pseudocode-container").forEach(function(el) {
          let pseudocodeOptions = {
            indentSize: el.dataset.indentSize,
            commentDelimiter: " " + el.dataset.commentDelimiter + " ",
            lineNumber: el.dataset.lineNumber.toLowerCase() === "true",
            lineNumberPunc: el.dataset.lineNumberPunc,
            noEnd: el.dataset.noEnd.toLowerCase() === "true",
            scopeLines: el.dataset.indentLines.toLowerCase() === "true",
            titlePrefix: el.dataset.captionPrefix,
          };
          pseudocode.renderElement(el.querySelector(".pseudocode"), pseudocodeOptions);
        });
        d.querySelectorAll(".pseudocode-container").forEach(function(el) {
          let captionSpan = el.querySelector(".ps-root > .ps-algorithm > .ps-line > .ps-keyword")
          if (captionSpan !== null) {
            let captionPrefix = el.dataset.captionPrefix + " ";
            let captionNumber = "";
            if (el.dataset.pseudocodeNumber) {
              captionNumber = el.dataset.pseudocodeNumber + " ";
              if (el.dataset.chapterLevel) {
                captionNumber = el.dataset.chapterLevel + "." + captionNumber;
              }
            }
            captionSpan.innerHTML = captionPrefix + captionNumber;
          }
        });
      }
      // pseudocode.js needs a math backend (KaTeX or MathJax) present *at the
      // moment* renderElement runs. This book renders math with MathJax loaded
      // via `defer`, so window.MathJax does not exist yet when this after-body
      // script executes at parse time — calling renderElement now throws
      // "No math backend found" and the raw LaTeX source stays on the page.
      // Wait for the math backend to be ready before rendering: KaTeX if it is
      // present synchronously, otherwise MathJax's startup promise (available
      // after the deferred MathJax script has run, by window 'load').
      function whenMathReady(cb) {
        if (window.katex) { cb(); return; }
        var mj = window.MathJax;
        if (mj && mj.startup && mj.startup.promise) { mj.startup.promise.then(cb); return; }
        window.addEventListener("load", function() {
          var m = window.MathJax;
          if (m && m.startup && m.startup.promise) { m.startup.promise.then(cb); }
          else { cb(); }
        });
      }
      whenMathReady(renderPseudocode);
    })(document);
    </script>
  
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>