<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>visual_debugging – ML Systems Interview Playbook</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../tinyml/README.md" rel="next">
<link href="../mobile/03_ship_and_update.html" rel="prev">
<link href="../assets/images/logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-f418161beb48e0141c760e455f12af2c.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-21c764a5dcc9b1c1f26ec6e6cb5ccc47.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-7ccbd0bd5ebd2ebc8632c0bb6ddfa566.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-21c764a5dcc9b1c1f26ec6e6cb5ccc47.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "/"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&amp;family=Outfit:wght@600;700&amp;family=JetBrains+Mono:wght@400;500&amp;display=swap" rel="stylesheet">


</head>

<body class="nav-sidebar floating nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-xl " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../assets/images/logo.png" alt="" class="navbar-logo light-content">
    <img src="../assets/images/logo.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Machine Learning Systems</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-interview-playbook" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Interview Playbook</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-interview-playbook">    
        <li>
    <a class="dropdown-item" href="../index.html"><i class="bi bi-shield-check" role="img">
</i> 
 <span class="dropdown-text">Playbook Hub</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../00_The_Architects_Rubric.html">
 <span class="dropdown-text">The Architect’s Rubric</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../NUMBERS.html">
 <span class="dropdown-text">Numbers Cheat Sheet</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../cloud/README.md">
 <span class="dropdown-text">☁️ Cloud Track</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../edge/README.md">
 <span class="dropdown-text">🤖 Edge Track</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../mobile/README.md">
 <span class="dropdown-text">📱 Mobile Track</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tinyml/README.md">
 <span class="dropdown-text">🔬 TinyML Track</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-read" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Read</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-read">    
        <li>
    <a class="dropdown-item" href="../book/vol1/"><i class="bi bi-journal" role="img">
</i> 
 <span class="dropdown-text">Volume I: Foundations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../book/vol2/"><i class="bi bi-journal" role="img">
</i> 
 <span class="dropdown-text">Volume II: At Scale</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../book/vol1/assets/downloads/Machine-Learning-Systems-Vol1.pdf" target="_blank"><i class="bi bi-file-pdf" role="img">
</i> 
 <span class="dropdown-text">Volume I PDF</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../book/vol1/assets/downloads/Machine-Learning-Systems-Vol1.epub" target="_blank"><i class="bi bi-journal-text" role="img">
</i> 
 <span class="dropdown-text">Volume I EPUB</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../book/vol2/assets/downloads/Machine-Learning-Systems-Vol2.pdf" target="_blank"><i class="bi bi-file-pdf" role="img">
</i> 
 <span class="dropdown-text">Volume II PDF</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../book/vol2/assets/downloads/Machine-Learning-Systems-Vol2.epub" target="_blank"><i class="bi bi-journal-text" role="img">
</i> 
 <span class="dropdown-text">Volume II EPUB</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-build" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Build</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-build">    
        <li>
    <a class="dropdown-item" href="../tinytorch/"><i class="bi bi-fire" role="img">
</i> 
 <span class="dropdown-text">TinyTorch</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../mlsysim/"><i class="bi bi-calculator" role="img">
</i> 
 <span class="dropdown-text">MLSys·IM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../labs/"><i class="bi bi-sliders" role="img">
</i> 
 <span class="dropdown-text">Interactive Labs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../kits/"><i class="bi bi-cpu" role="img">
</i> 
 <span class="dropdown-text">Hardware Kits</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-teach" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Teach</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-teach">    
        <li>
    <a class="dropdown-item" href="../slides/"><i class="bi bi-easel" role="img">
</i> 
 <span class="dropdown-text">Lecture Slides</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../instructors/"><i class="bi bi-person-video3" role="img">
</i> 
 <span class="dropdown-text">Instructor Hub</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/harvard-edge/cs249r_book/tree/dev/interviews" target="_blank"><i class="bi bi-mortarboard" role="img">
</i> 
 <span class="dropdown-text">Interview Prep</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-community" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Community</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-community">    
        <li>
    <a class="dropdown-item" href="../newsletter/"><i class="bi bi-envelope" role="img">
</i> 
 <span class="dropdown-text">Newsletter</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../community/"><i class="bi bi-globe" role="img">
</i> 
 <span class="dropdown-text">Global Network</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../community/#events"><i class="bi bi-calendar-event" role="img">
</i> 
 <span class="dropdown-text">Workshops &amp; Events</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../community/#partners"><i class="bi bi-people" role="img">
</i> 
 <span class="dropdown-text">Partners &amp; Sponsors</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../about/#story"><i class="bi bi-book" role="img">
</i> 
 <span class="dropdown-text">Our Story</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../about/#mission"><i class="bi bi-bullseye" role="img">
</i> 
 <span class="dropdown-text">Mission</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../about/#milestones"><i class="bi bi-clock-history" role="img">
</i> 
 <span class="dropdown-text">Milestones</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../about/#team"><i class="bi bi-person-lines-fill" role="img">
</i> 
 <span class="dropdown-text">People</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../about/#contributors"><i class="bi bi-people" role="img">
</i> 
 <span class="dropdown-text">Contributors</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../about/#license"><i class="bi bi-cc-circle" role="img">
</i> 
 <span class="dropdown-text">License</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://opencollective.com/mlsysbook" target="_blank"> <i class="bi bi-heart" role="img">
</i> 
<span class="menu-text">Support</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/harvard-edge/cs249r_book" target="_blank"> <i class="bi bi-star" role="img">
</i> 
<span class="menu-text">Star</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../#subscribe"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text">Subscribe</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-github" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text">GitHub</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-github">    
        <li>
    <a class="dropdown-item" href="https://github.com/harvard-edge/cs249r_book/discussions" target="_blank"><i class="bi bi-chat" role="img">
</i> 
 <span class="dropdown-text">Discussions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/harvard-edge/cs249r_book" target="_blank"><i class="bi bi-pencil" role="img">
</i> 
 <span class="dropdown-text">Edit this page</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/harvard-edge/cs249r_book/issues/new" target="_blank"><i class="bi bi-bug" role="img">
</i> 
 <span class="dropdown-text">Report an issue</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/harvard-edge/cs249r_book" target="_blank"><i class="bi bi-code" role="img">
</i> 
 <span class="dropdown-text">View source</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../mobile/README.md">📱 Mobile Track</a></li><li class="breadcrumb-item"><a href="../mobile/04_visual_debugging.html">Visual Architecture Debugging</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Playbook Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../00_The_Architects_Rubric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Architect’s Rubric</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../NUMBERS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Numbers Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../cloud/README.md" class="sidebar-item-text sidebar-link">
 <span class="menu-text">☁️ Cloud Track</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cloud/01_single_machine.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Single Machine</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cloud/02_distributed_systems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Distributed System</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cloud/03_serving_stack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Serving Stack</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cloud/04_production_ops.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Production System</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cloud/05_visual_debugging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visual Architecture Debugging</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../edge/README.md" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🤖 Edge Track</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../edge/01_hardware_platform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Hardware Platform</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../edge/02_realtime_pipeline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Real-Time Pipeline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../edge/03_deployed_system.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Deployed System</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../edge/04_visual_debugging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visual Architecture Debugging</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../mobile/README.md" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📱 Mobile Track</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../mobile/01_device_hardware.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Device &amp; SoC</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../mobile/02_app_experience.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The App Experience</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../mobile/03_ship_and_update.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ship &amp; Update</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../mobile/04_visual_debugging.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Visual Architecture Debugging</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../tinyml/README.md" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🔬 TinyML Track</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tinyml/01_microcontroller.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Microcontroller</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tinyml/02_sensing_pipeline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Sensing Pipeline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tinyml/03_deployed_device.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Deployed Device</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tinyml/04_visual_debugging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visual Architecture Debugging</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#visual-architecture-debugging" id="toc-visual-architecture-debugging" class="nav-link active" data-scroll-target="#visual-architecture-debugging">Visual Architecture Debugging</a>
  <ul class="collapse">
  <li><a href="#synchronous-download-blocks-the-critical-path" id="toc-synchronous-download-blocks-the-critical-path" class="nav-link" data-scroll-target="#synchronous-download-blocks-the-critical-path">Synchronous Download Blocks the Critical Path</a></li>
  <li><a href="#npu-cpu-ping-pong-creates-pipeline-bubbles" id="toc-npu-cpu-ping-pong-creates-pipeline-bubbles" class="nav-link" data-scroll-target="#npu-cpu-ping-pong-creates-pipeline-bubbles">NPU-CPU Ping-Pong Creates Pipeline Bubbles</a></li>
  <li><a href="#ml-model-camera-isp-compete-for-the-same-ram-pool" id="toc-ml-model-camera-isp-compete-for-the-same-ram-pool" class="nav-link" data-scroll-target="#ml-model-camera-isp-compete-for-the-same-ram-pool">ML Model + Camera ISP Compete for the Same RAM Pool</a></li>
  <li><a href="#benchmarking-peak-performance-not-sustained-performance" id="toc-benchmarking-peak-performance-not-sustained-performance" class="nav-link" data-scroll-target="#benchmarking-peak-performance-not-sustained-performance">Benchmarking Peak Performance, Not Sustained Performance</a></li>
  <li><a href="#three-copies-of-the-same-backbone" id="toc-three-copies-of-the-same-backbone" class="nav-link" data-scroll-target="#three-copies-of-the-same-backbone">Three Copies of the Same Backbone</a></li>
  <li><a href="#no-atomicity-guarantee-for-model-updates" id="toc-no-atomicity-guarantee-for-model-updates" class="nav-link" data-scroll-target="#no-atomicity-guarantee-for-model-updates">No Atomicity Guarantee for Model Updates</a></li>
  <li><a href="#the-cpu-wake-lock-tax" id="toc-the-cpu-wake-lock-tax" class="nav-link" data-scroll-target="#the-cpu-wake-lock-tax">The CPU Wake-Lock Tax</a></li>
  <li><a href="#the-shared-silicon-thermal-envelope" id="toc-the-shared-silicon-thermal-envelope" class="nav-link" data-scroll-target="#the-shared-silicon-thermal-envelope">The Shared Silicon Thermal Envelope</a></li>
  <li><a href="#the-cellular-radio-wake-dominates-power-not-the-model" id="toc-the-cellular-radio-wake-dominates-power-not-the-model" class="nav-link" data-scroll-target="#the-cellular-radio-wake-dominates-power-not-the-model">The Cellular Radio Wake Dominates Power, Not the Model</a></li>
  <li><a href="#uma-bandwidth-contention" id="toc-uma-bandwidth-contention" class="nav-link" data-scroll-target="#uma-bandwidth-contention">UMA Bandwidth Contention</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../mobile/README.md">📱 Mobile Track</a></li><li class="breadcrumb-item"><a href="../mobile/04_visual_debugging.html">Visual Architecture Debugging</a></li></ol></nav></header>





<section id="visual-architecture-debugging" class="level1">
<h1>Visual Architecture Debugging</h1>
<div data-align="center">
<p><a href="../README.md">🏠 Home</a> · <a href="../00_The_Architects_Rubric.html">📋 Rubric</a> · <a href="../cloud/README.md">☁️ Cloud</a> · <a href="../edge/README.md">🤖 Edge</a> · <b>📱 Mobile</b> · <a href="../tinyml/README.md">🔬 TinyML</a></p>
</div>
<hr>
<p><em>Can you spot the bottleneck in a mobile system diagram?</em></p>
<p>Mobile system architecture diagrams with hidden bottlenecks.</p>
<blockquote class="blockquote">
<p><strong><a href="https://github.com/harvard-edge/cs249r_book/edit/dev/interviews/mobile/04_visual_debugging.md">➕ Add a Flashcard</a></strong> (Edit in Browser) — see <a href="../README.md#question-format">README</a> for the template.</p>
</blockquote>
<hr>
<details>
<summary>
<b><img src="https://img.shields.io/badge/Level-L3_Junior-brightgreen?style=flat-square" alt="Level 1" align="center"> The Launch Blocker</b> · <code>serving</code> <code>ux</code>
</summary>
<section id="synchronous-download-blocks-the-critical-path" class="level3">
<h3 class="anchored" data-anchor-id="synchronous-download-blocks-the-critical-path">Synchronous Download Blocks the Critical Path</h3>
<pre class="mermaid"><code>%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'monospace', 'primaryColor': '#ffffff', 'edgeLabelBackground':'#ffffff'}}}%%
graph TD
    classDef safe fill:#e0f2fe,stroke:#2563eb,stroke-width:2px,color:#1e3a8a
    classDef danger fill:#fee2e2,stroke:#dc2626,stroke-width:2px,color:#991b1b,stroke-dasharray: 5 5
    classDef process fill:#f3f4f6,stroke:#4b5563,stroke-width:2px,color:#1f2937

    T1["Launch: App UI Loaded"]:::safe
    T2["Step 1: Download Model&lt;br/&gt;(Wait: 60s)"]:::danger
    T3["Step 2: Validate Checksum&lt;br/&gt;(Wait: 2s)"]:::process
    T4["Step 3: Compile for NPU&lt;br/&gt;(Wait: 8s)"]:::process
    T5["READY: User can Translate"]:::safe

    T1 --&gt; T2
    T2 --&gt; T3
    T3 --&gt; T4
    T4 --&gt; T5

    Note["🚨 CRITICAL FRICTION&lt;br/&gt;Total blocked time: 70 seconds&lt;br/&gt;Status: 95% User Abandonment"]:::danger
    T2 --- Note</code></pre>
<ul>
<li><p><strong>Interviewer:</strong> “A user downloads your new LLM-powered translation app. Upon first launch, the app shows a spinner for 70 seconds while it prepares the model. Based on the launch timeline, why are you seeing a 95% abandonment rate?”</p>
<details>
<summary>
<p><b>🔍 Reveal Answer</b></p>
</summary>
<p><strong>Common Mistake:</strong> “Show a progress bar instead of a spinner.” A progress bar is better UX, but 70 seconds is too long regardless of visual feedback.</p>
<p><strong>Realistic Solution:</strong> The architecture has a <strong>Synchronous Dependency on the Critical Path</strong>. The app forces users to wait for sequential download, validation, and compilation before any functionality is available. The fix is a <strong>Progressive Launch Architecture</strong>: ship a tiny fallback model (~3 MB) in the app bundle for instant value, while downloading and compiling the high-quality model in the background.</p>
<blockquote class="blockquote">
<p><strong>Napkin Math:</strong> User attention span for a new app launch is ~2-5 seconds. A 70-second block is 14-35x longer than the tolerance threshold of a typical mobile user.</p>
</blockquote>
<p>📖 <strong>Deep Dive:</strong> <a href="https://harvard-edge.github.io/cs249r_book_dev/contents/model_serving/model_serving.html">Model Serving</a></p>
</details></li>
</ul>
</section></details>
<details>
<summary>
<b><img src="https://img.shields.io/badge/Level-L4_Mid-blue?style=flat-square" alt="Level 2" align="center"> The Operator Gap</b> · <code>compilation</code> <code>latency</code>
</summary>
</details></section>
<section id="npu-cpu-ping-pong-creates-pipeline-bubbles" class="level3">
<h3 class="anchored" data-anchor-id="npu-cpu-ping-pong-creates-pipeline-bubbles">NPU-CPU Ping-Pong Creates Pipeline Bubbles</h3>
<pre class="mermaid"><code>%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'monospace', 'primaryColor': '#ffffff', 'edgeLabelBackground':'#ffffff'}}}%%
graph LR
    classDef npu fill:#e0f2fe,stroke:#2563eb,stroke-width:2px,color:#1e3a8a
    classDef cpu fill:#f3f4f6,stroke:#4b5563,stroke-width:2px,color:#1f2937
    classDef bounce fill:#fee2e2,stroke:#dc2626,stroke-width:2px,color:#991b1b,stroke-dasharray: 5 5

    NPU1["NPU Segment 1&lt;br/&gt;(8 Conv Blocks)"]:::npu
    DMA1["DMA Bounce&lt;br/&gt;(Unsupported GELU)"]:::bounce
    NPU2["NPU Segment 2&lt;br/&gt;(4 Conv Blocks)"]:::npu
    DMA2["DMA Bounce&lt;br/&gt;(Dynamic Shape)"]:::bounce
    NPU3["NPU Segment 3&lt;br/&gt;(4 Conv Blocks)"]:::npu

    NPU1 --&gt;|1.2ms| DMA1
    DMA1 --&gt;|1.2ms| NPU2
    NPU2 --&gt;|1.2ms| DMA2
    DMA2 --&gt;|1.2ms| NPU3

    Note["🚨 HIDDEN OVERHEAD&lt;br/&gt;4.8ms spent in DMA&lt;br/&gt;32% of total latency"]:::bounce</code></pre>
<ul>
<li><p><strong>Interviewer:</strong> “You are deploying a model to a mobile NPU. The math should only take 10ms, but the actual inference latency is 15ms. You find two unsupported operators in your graph. Based on the DMA flow, why are these two ops causing a 50% latency penalty?”</p>
<details>
<summary>
<p><b>🔍 Reveal Answer</b></p>
</summary>
<p><strong>Common Mistake:</strong> “The NPU is slow — use a bigger model.” The NPU compute is fine. The overhead is in the data movement.</p>
<p><strong>Realistic Solution:</strong> You are hitting <strong>Graph Partitioning Overhead</strong>. Each unsupported operator forces the graph to ‘ping-pong’ data from the NPU to the CPU and back via DMA. This incurs a latency tax for the transfer and leaves the NPU idle while the CPU processes the single op. The fix is to eliminate partition boundaries by replacing unsupported ops with approximations (e.g., Sigmoid approximation for GELU) or static-shape equivalents.</p>
<blockquote class="blockquote">
<p><strong>Napkin Math:</strong> Each NPU-CPU-NPU round-trip costs ~2.4ms in DMA overhead. With 2 such bounces, you spend 4.8ms just moving data—roughly 32% of your 15ms total budget—without doing any significant math.</p>
</blockquote>
<p>📖 <strong>Deep Dive:</strong> <a href="https://harvard-edge.github.io/cs249r_book_dev/contents/frameworks/frameworks.html">ML Frameworks</a></p>
</details></li>
</ul>

<details>
<summary>
<b><img src="https://img.shields.io/badge/Level-L4_Mid-blue?style=flat-square" alt="Level 2" align="center"> The Jetsam Guillotine</b> · <code>memory-hierarchy</code> <code>fault-tolerance</code>
</summary>
</details></section>
<section id="ml-model-camera-isp-compete-for-the-same-ram-pool" class="level3">
<h3 class="anchored" data-anchor-id="ml-model-camera-isp-compete-for-the-same-ram-pool">ML Model + Camera ISP Compete for the Same RAM Pool</h3>
<pre class="mermaid"><code>%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'monospace', 'primaryColor': '#ffffff', 'edgeLabelBackground':'#ffffff'}}}%%
graph TD
    classDef app fill:#e0f2fe,stroke:#2563eb,stroke-width:2px,color:#1e3a8a
    classDef sys fill:#f3f4f6,stroke:#4b5563,stroke-width:2px,color:#1f2937
    classDef danger fill:#fee2e2,stroke:#dc2626,stroke-width:2px,color:#991b1b,stroke-dasharray: 5 5

    subgraph "Physical RAM (4 GB Total)"
        direction TB
        iOS["iOS + System Services&lt;br/&gt;(1.5 GB)"]:::sys
        ISP["Camera ISP Service&lt;br/&gt;(1.2 GB)"]:::sys
        App["Your App&lt;br/&gt;(822 MB)"]:::app
        OOM["OUT OF MEMORY&lt;br/&gt;(Demand: 4.7 GB)"]:::danger
    end

    App -- "Allocation" --&gt; OOM
    ISP -- "Allocation" --&gt; OOM
    OOM -- "SIGKILL (Jetsam)" --&gt; App

    Note["🚨 SILENT KILLER&lt;br/&gt;ISP memory is invisible to your app&lt;br/&gt;Total demand exceeds 4GB limit"]:::danger</code></pre>
<ul>
<li><p><strong>Interviewer:</strong> “Your AR app crashes with a ‘SIGKILL’ (Jetsam kill) when users take a high-resolution photo, even though your app is only using 822 MB of its 2 GB memory limit. Based on the RAM diagram, what is the ‘invisible’ resource consumer causing the OS to kill your process?”</p>
<details>
<summary>
<p><b>🔍 Reveal Answer</b></p>
</summary>
<p><strong>Common Mistake:</strong> “The model is too big — quantize it.” Quantization helps, but the real issue is that the camera ISP’s memory allocation is invisible to your app and uncontrollable.</p>
<p><strong>Realistic Solution:</strong> You are hitting a <strong>Shared Resource RAM Collision</strong>. The camera ISP service runs in a separate process but shares the same physical RAM pool. During photo capture, the ISP HDR pipeline can consume &gt;1.2 GB. When combined with the OS and your app, total demand exceeds 4 GB, and the OS kills the app to protect the camera. The fix is to use <strong>mmap</strong> for weights (allowing OS eviction), reduce camera resolution during inference, or sequentialize the capture and ML phases.</p>
<blockquote class="blockquote">
<p><strong>Napkin Math:</strong> Total Memory = 1.5 GB (OS) + 1.2 GB (ISP) + 0.82 GB (App) = 3.52 GB. This is dangerously close to the 4 GB limit. Any background task (like a notification or a message) will push the system over the edge.</p>
</blockquote>
<p>📖 <strong>Deep Dive:</strong> <a href="https://harvard-edge.github.io/cs249r_book_dev/contents/model_serving/model_serving.html">Model Serving</a></p>
</details></li>
</ul>

<details>
<summary>
<b><img src="https://img.shields.io/badge/Level-L4_Mid-blue?style=flat-square" alt="Level 2" align="center"> The Burst Benchmarking Illusion</b> · <code>roofline</code> <code>power</code>
</summary>
</details></section>
<section id="benchmarking-peak-performance-not-sustained-performance" class="level3">
<h3 class="anchored" data-anchor-id="benchmarking-peak-performance-not-sustained-performance">Benchmarking Peak Performance, Not Sustained Performance</h3>
<pre class="mermaid"><code>%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'monospace', 'primaryColor': '#ffffff', 'edgeLabelBackground':'#ffffff'}}}%%
graph TD
    classDef peak fill:#e0f2fe,stroke:#2563eb,stroke-width:2px,color:#1e3a8a
    classDef throttle fill:#fee2e2,stroke:#dc2626,stroke-width:2px,color:#991b1b,stroke-dasharray: 5 5
    classDef process fill:#f3f4f6,stroke:#4b5563,stroke-width:2px,color:#1f2937

    T1["0-30s: PEAK STATE&lt;br/&gt;(45 TOPS / 30 FPS)"]:::peak
    T2["30-60s: HEATING&lt;br/&gt;(SoC Junction @ 80°C)"]:::process
    T3["60s+: THERMAL THROTTLE&lt;br/&gt;(20 TOPS / 12 FPS)"]:::throttle

    T1 --&gt; T2
    T2 --&gt; T3

    Note["🚨 BENCHMARKING ERROR&lt;br/&gt;Model designed for Peak (30 FPS)&lt;br/&gt;Field reality: Sustained (12 FPS)"]:::throttle
    T3 --- Note</code></pre>
<ul>
<li><p><strong>Interviewer:</strong> “Your mobile model runs at 30 FPS during internal demos, but users complain that it slows down to 12 FPS after a minute of use. Based on the performance timeline, what physical protection mechanism is engaging inside the smartphone?”</p>
<details>
<summary>
<p><b>🔍 Reveal Answer</b></p>
</summary>
<p><strong>Common Mistake:</strong> “The phone is defective” or “Add a cooling fan.” You can’t attach a fan to a user’s phone. The phone is working exactly as designed — DVFS (Dynamic Voltage and Frequency Scaling) protects the SoC from thermal damage.</p>
<p><strong>Realistic Solution:</strong> You are hitting the <strong>Sustained Thermal Envelope</strong>. Mobile SoCs support high TOPS only for short “bursts.” For continuous inference, the device throttles to its sustained thermal design power (sTDP), often 40-60% of peak. The fix is to target sustained performance (e.g., design for 20 TOPS, not 45 TOPS peak), implement adaptive frame rates based on <code>ThermalState</code>, or use the NPU instead of the GPU to halve heat generation.</p>
<blockquote class="blockquote">
<p><strong>Napkin Math:</strong> Sustained TOPS is typically ~50% of Peak. If your model requires 100% of peak TOPS to hit 30 FPS, you are guaranteed to drop to 15 FPS once the thermal envelope is saturated (~60 seconds).</p>
</blockquote>
<p>📖 <strong>Deep Dive:</strong> <a href="https://harvard-edge.github.io/cs249r_book_dev/contents/hw_acceleration/hw_acceleration.html">Hardware Acceleration</a></p>
</details></li>
</ul>

<details>
<summary>
<b><img src="https://img.shields.io/badge/Level-L4_Mid-blue?style=flat-square" alt="Level 2" align="center"> The Backbone Bloat</b> · <code>model-cost</code> <code>memory-hierarchy</code>
</summary>
</details></section>
<section id="three-copies-of-the-same-backbone" class="level3">
<h3 class="anchored" data-anchor-id="three-copies-of-the-same-backbone">Three Copies of the Same Backbone</h3>
<pre class="mermaid"><code>%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'monospace', 'primaryColor': '#ffffff', 'edgeLabelBackground':'#ffffff'}}}%%
graph TD
    classDef weight fill:#ffedd5,stroke:#ea580c,stroke-width:2px,color:#9a3412
    classDef bottleneck fill:#fee2e2,stroke:#dc2626,stroke-width:2px,color:#991b1b,stroke-dasharray: 5 5

    subgraph "VRAM (Current: 171 MB)"
        direction LR
        subgraph "Team A"
            B1["Backbone 1&lt;br/&gt;(12 MB)"]:::bottleneck
            H1["Face Head"]
        end
        subgraph "Team B"
            B2["Backbone 2&lt;br/&gt;(12 MB)"]:::bottleneck
            H2["Mesh Head"]
        end
        subgraph "Team C"
            B3["Backbone 3&lt;br/&gt;(12 MB)"]:::bottleneck
            H3["Seg Head"]
        end
    end

    Note["🚨 REDUNDANCY ERROR&lt;br/&gt;Identical weights loaded 3x&lt;br/&gt;Shared activations computed 3x"]:::bottleneck</code></pre>
<ul>
<li><p><strong>Interviewer:</strong> “Your mobile app has three different computer vision features (Face Detection, Face Mesh, and Segmentation). All three use the same MobileNetV3 backbone. Based on the VRAM diagram, what is the ‘efficiency gap’ in your model loading strategy?”</p>
<details>
<summary>
<p><b>🔍 Reveal Answer</b></p>
</summary>
<p><strong>Common Mistake:</strong> “Run the models in parallel on different cores.” The phone has one NPU — parallel execution doesn’t help. And you’d still waste 171 MB of memory.</p>
<p><strong>Realistic Solution:</strong> You have <strong>Backbone Redundancy</strong>. The app loads three identical copies of the backbone weights and computes the same features three times per frame. The fix is a <strong>Multi-Task Architecture with Shared Backbone</strong>: load the backbone once (12 MB), run it once (6ms), and branch into three lightweight task heads. This reduces memory by 64% and latency by 40%.</p>
<blockquote class="blockquote">
<p><strong>Napkin Math:</strong> Current: 3 backbones × 12 MB = 36 MB weights. Shared: 1 backbone × 12 MB = 12 MB. Latency: 3 × 6ms = 18ms (sequential backbone runs) vs 1 × 6ms = 6ms.</p>
</blockquote>
<p>📖 <strong>Deep Dive:</strong> <a href="https://harvard-edge.github.io/cs249r_book_dev/contents/network_architectures/network_architectures.html">Network Architectures</a></p>
</details></li>
</ul>

<details>
<summary>
<b><img src="https://img.shields.io/badge/Level-L4_Mid-blue?style=flat-square" alt="Level 2" align="center"> The Frankenstein Model</b> · <code>deployment</code> <code>fault-tolerance</code>
</summary>
</details></section>
<section id="no-atomicity-guarantee-for-model-updates" class="level3">
<h3 class="anchored" data-anchor-id="no-atomicity-guarantee-for-model-updates">No Atomicity Guarantee for Model Updates</h3>
<pre class="mermaid"><code>%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'monospace', 'primaryColor': '#ffffff', 'edgeLabelBackground':'#ffffff'}}}%%
graph LR
    classDef safe fill:#e0f2fe,stroke:#2563eb,stroke-width:2px,color:#1e3a8a
    classDef partial fill:#ffedd5,stroke:#ea580c,stroke-width:2px,color:#9a3412
    classDef danger fill:#fee2e2,stroke:#dc2626,stroke-width:2px,color:#991b1b,stroke-dasharray: 5 5

    subgraph "Active Model File"
        L1["Layer 1 (v2.0 NEW)"]:::safe
        L2["Layer 2 (v2.0 NEW)"]:::safe
        LX["CRASH / POWER LOST"]:::danger
        L3["Layer 3 (v1.0 OLD)"]:::partial
        L4["Layer 4 (v1.0 OLD)"]:::partial
    end

    Note["🚨 CORRUPT STATE&lt;br/&gt;Frankenstein Model: Mixed Weights&lt;br/&gt;Output: Numerical Garbage"]:::danger</code></pre>
<ul>
<li><p><strong>Interviewer:</strong> “During a background model update on a user’s phone, the device suddenly reboots. Upon next launch, the app doesn’t crash, but the ML model produces nonsensical ‘garbage’ outputs. Based on the file-write diagram, what state is the model file in?”</p>
<details>
<summary>
<p><b>🔍 Reveal Answer</b></p>
</summary>
<p><strong>Common Mistake:</strong> “Check battery level before training.” Battery checks don’t prevent interruptions like OS kills or reboots.</p>
<p><strong>Realistic Solution:</strong> You have a <strong>Frankenstein Model</strong> caused by non-atomic updates. The pipeline wrote the updated model directly to the active file. If interrupted, the file contains a mix of new and old layers, which is numerically invalid. The fix is <strong>Atomic Promotion (Shadow Copy)</strong>: download/train the model in a temporary directory, and only after validation is complete, use an atomic <code>rename()</code> call to replace the active model file.</p>
<blockquote class="blockquote">
<p><strong>Napkin Math:</strong> If 60% of layers are v2.0 and 40% are v1.0, the feature map distribution from Layer 2 will not match the weights expected by Layer 3, leading to catastrophic error propagation.</p>
</blockquote>
<p>📖 <strong>Deep Dive:</strong> <a href="https://harvard-edge.github.io/cs249r_book_dev/contents/ml_ops/ml_ops.html">ML Operations</a></p>
</details></li>
</ul>

<details>
<summary>
<b><img src="https://img.shields.io/badge/Level-L4_Mid-blue?style=flat-square" alt="Level 2" align="center"> The CPU Wake-Lock Tax</b> · <code>sustainable-ai</code> <code>power</code>
</summary>
</details></section>
<section id="the-cpu-wake-lock-tax" class="level3">
<h3 class="anchored" data-anchor-id="the-cpu-wake-lock-tax">The CPU Wake-Lock Tax</h3>
<pre class="mermaid"><code>%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'monospace', 'primaryColor': '#ffffff', 'edgeLabelBackground':'#ffffff'}}}%%
graph TD
    classDef sleep fill:#f3f4f6,stroke:#94a3b8,stroke-width:1px,color:#64748b
    classDef active fill:#ffedd5,stroke:#ea580c,stroke-width:2px,color:#9a3412
    classDef danger fill:#fee2e2,stroke:#dc2626,stroke-width:2px,color:#991b1b,stroke-dasharray: 5 5

    subgraph "Application Processor (AP)"
        CPU["Cortex-A Core&lt;br/&gt;(AWAKE)"]:::active
        RAM["DDR RAM&lt;br/&gt;(POWERED)"]:::active
        Bus["Memory Bus&lt;br/&gt;(ACTIVE)"]:::active
    end

    subgraph "Always-On Domain (AOD)"
        DSP["DSP / micro-NPU&lt;br/&gt;(IDLE)"]:::sleep
    end

    Mic["Microphone"] --&gt; CPU
    Note["🚨 POWER TAX&lt;br/&gt;AP held awake via Wake-Lock&lt;br/&gt;Basal power: 80mW (vs 1mW sleep)"]:::danger</code></pre>
<ul>
<li><p><strong>Interviewer:</strong> “You deploy a simple wake-word detection model. Even though the model uses very little CPU, users report that the app is the top battery consumer on their device. Based on the power domain diagram, where is the energy going?”</p>
<details>
<summary>
<p><b>🔍 Reveal Answer</b></p>
</summary>
<p><strong>Common Mistake:</strong> “The model needs to be quantized to INT8 so it uses less power.” The model’s compute cost is negligible; the power is being burned by the hardware state required to execute it.</p>
<p><strong>Realistic Solution:</strong> You are suffering from <strong>Application Processor Wake-Lock Tax</strong>. To run the model on the main CPU, the OS must hold a wake-lock, powering up the high-power CPU rails and DDR RAM. This prevents the phone from entering Deep Sleep. The fix is to push always-on models down to the <strong>Always-On Domain (AOD) / DSP</strong>, which reads the microphone directly into tiny SRAM and only wakes the main AP if the wake-word is detected.</p>
<blockquote class="blockquote">
<p><strong>Napkin Math:</strong> Basal AP power is ~80 mW. DSP power is ~1 mW. By failing to delegate to the AOD, you are using 80x more power than necessary just to keep the lights on for a simple task.</p>
</blockquote>
<p>📖 <strong>Deep Dive:</strong> <a href="https://harvard-edge.github.io/cs249r_book_dev/contents/sustainable_ai/sustainable_ai.html">Sustainable AI</a></p>
</details></li>
</ul>

<details>
<summary>
<b><img src="https://img.shields.io/badge/Level-L4_Mid-blue?style=flat-square" alt="Level 2" align="center"> The Silicon Shared Oven</b> · <code>sustainable-ai</code> <code>power</code>
</summary>
</details></section>
<section id="the-shared-silicon-thermal-envelope" class="level3">
<h3 class="anchored" data-anchor-id="the-shared-silicon-thermal-envelope">The Shared Silicon Thermal Envelope</h3>
<pre class="mermaid"><code>%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'monospace', 'primaryColor': '#ffffff', 'edgeLabelBackground':'#ffffff'}}}%%
graph TD
    classDef cooling fill:#e0f2fe,stroke:#2563eb,stroke-width:2px,color:#1e3a8a
    classDef heat fill:#ffedd5,stroke:#ea580c,stroke-width:2px,color:#9a3412
    classDef danger fill:#fee2e2,stroke:#dc2626,stroke-width:2px,color:#991b1b,stroke-dasharray: 5 5

    subgraph "Single Silicon Die (SoC)"
        direction LR
        GPU["GPU&lt;br/&gt;(Heavy 3D Game)"]:::danger
        CPU["CPU&lt;br/&gt;(Background)"]:::heat
        NPU["NPU&lt;br/&gt;(Translation)"]:::danger
    end

    Skin["Phone Surface&lt;br/&gt;(Limit: 45°C)"]

    GPU -- "Massive Heat" --&gt; Skin
    CPU -- "Heat" --&gt; Skin
    Skin -- "🚨 THERMAL EVENT" --&gt; SoC_Control["DVFS Controller"]
    SoC_Control -- "GLOBAL THROTTLE" --&gt; GPU
    SoC_Control -- "GLOBAL THROTTLE" --&gt; NPU

    Note["🚨 SILENT THROTTLE&lt;br/&gt;NPU latency triples because&lt;br/&gt;GPU generates the heat"]:::danger</code></pre>
<ul>
<li><p><strong>Interviewer:</strong> “Your real-time translation app works perfectly until the user starts a 3D game in picture-in-picture mode. Suddenly, your NPU translation latency triples. Based on the SoC diagram, why is the game affecting the NPU speed?”</p>
<details>
<summary>
<p><b>🔍 Reveal Answer</b></p>
</summary>
<p><strong>Common Mistake:</strong> “The game is stealing NPU cycles.” The game uses the GPU, not the NPU. They are separate physical cores.</p>
<p><strong>Realistic Solution:</strong> You are hitting <strong>Global Thermal Throttling</strong>. In a mobile SoC, all cores share the same silicon die and thermal envelope. When the GPU generates massive heat from a game, the system’s DVFS controller downclocks <em>the entire SoC</em>—including the NPU—to stay within safe skin-temperature limits. The fix is to use hyper-optimized, low-power models that can still meet deadlines even when the SoC is forced into its lowest frequency state.</p>
<blockquote class="blockquote">
<p><strong>Napkin Math:</strong> A phone can only dissipate ~3-5 Watts sustained. If a 3D game pulls 4 Watts, the NPU is left with &lt;1 Watt of thermal margin, triggering immediate frequency capping.</p>
</blockquote>
<p>📖 <strong>Deep Dive:</strong> <a href="https://harvard-edge.github.io/cs249r_book_dev/contents/sustainable_ai/sustainable_ai.html">Sustainable AI</a></p>
</details></li>
</ul>

<details>
<summary>
<b><img src="https://img.shields.io/badge/Level-L5_Senior-yellow?style=flat-square" alt="Level 3" align="center"> The Radio Energy Wall</b> · <code>sustainable-ai</code> <code>power</code>
</summary>
</details></section>
<section id="the-cellular-radio-wake-dominates-power-not-the-model" class="level3">
<h3 class="anchored" data-anchor-id="the-cellular-radio-wake-dominates-power-not-the-model">The Cellular Radio Wake Dominates Power, Not the Model</h3>
<pre class="mermaid"><code>%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'monospace', 'primaryColor': '#ffffff', 'edgeLabelBackground':'#ffffff'}}}%%
graph TD
    classDef model fill:#e0f2fe,stroke:#2563eb,stroke-width:2px,color:#1e3a8a
    classDef cpu fill:#ffedd5,stroke:#ea580c,stroke-width:2px,color:#9a3412
    classDef radio fill:#fee2e2,stroke:#dc2626,stroke-width:2px,color:#991b1b,stroke-dasharray: 5 5

    subgraph "Power Budget (mW)"
        direction TB
        M["ML Model Inference&lt;br/&gt;(3 mW)"]:::model
        C["CPU Always-On&lt;br/&gt;(80 mW)"]:::cpu
        R["Cellular Radio Wake&lt;br/&gt;(800 mW)"]:::radio
    end

    Note["🚨 ENERGY MISMATCH&lt;br/&gt;Radio uses 266x more power than ML&lt;br/&gt;Waking every 5m destroys battery"]:::radio</code></pre>
<ul>
<li><p><strong>Interviewer:</strong> “You optimize your activity-tracking model down to 3 mW. However, the app still drains the battery by 10% per hour because it uploads labels to your server every 5 minutes. Based on the power breakdown, where is your optimization effort being wasted?”</p>
<details>
<summary>
<p><b>🔍 Reveal Answer</b></p>
</summary>
<p><strong>Common Mistake:</strong> “Retrain the model to be even smaller.” The model’s 3 mW is already negligible compared to the system overhead.</p>
<p><strong>Realistic Solution:</strong> You are hitting the <strong>Radio Wake Overhead</strong>. The cellular radio consumes ~800 mW every time it wakes from idle. Waking it every 5 minutes for a tiny payload prevents the radio from staying in its low-power state. The fix is <strong>Batching and Delegation</strong>: buffer results locally and upload once per hour, and use the OS’s low-power activity co-processor (like Apple’s M-series) instead of a custom always-on CPU loop.</p>
<blockquote class="blockquote">
<p><strong>Napkin Math:</strong> Radio: 800 mW × 10s (wake + tail) × 12 times/hr = 26.7 mWh. Model: 3 mW × 1 hr = 3 mWh. The radio wake is ~9x more expensive than the actual ML work.</p>
</blockquote>
<p>📖 <strong>Deep Dive:</strong> <a href="https://harvard-edge.github.io/cs249r_book_dev/contents/sustainable_ai/sustainable_ai.html">Sustainable AI</a></p>
</details></li>
</ul>

<details>
<summary>
<b><img src="https://img.shields.io/badge/Level-L5_Senior-yellow?style=flat-square" alt="Level 3" align="center"> The UMA Bandwidth Wall</b> · <code>model-cost</code> <code>memory-hierarchy</code>
</summary>
</details></section>
<section id="uma-bandwidth-contention" class="level3">
<h3 class="anchored" data-anchor-id="uma-bandwidth-contention">UMA Bandwidth Contention</h3>
<pre class="mermaid"><code>%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'monospace', 'primaryColor': '#ffffff', 'edgeLabelBackground':'#ffffff'}}}%%
graph TD
    classDef device fill:#e0f2fe,stroke:#2563eb,stroke-width:2px,color:#1e3a8a
    classDef memory fill:#ffedd5,stroke:#ea580c,stroke-width:2px,color:#9a3412
    classDef bottleneck fill:#fee2e2,stroke:#dc2626,stroke-width:4px,color:#991b1b,stroke-dasharray: 5 5

    Disp["Display Controller&lt;br/&gt;(120Hz Refresh)"]:::device
    GPU["GPU&lt;br/&gt;(Render Framebuffer)"]:::device
    NPU["NPU&lt;br/&gt;(Style Transfer Model)"]:::device

    subgraph "Unified Memory Architecture (UMA)"
        Bus[["Shared Memory Bus&lt;br/&gt;(ARB: Display Priority)"]]:::bottleneck
    end

    RAM[("System RAM (LPDDR5)")]:::memory

    Disp --&gt;|High BW / High Priority| Bus
    GPU --&gt;|High BW| Bus
    NPU --&gt;|Wait / Starved| Bus
    Bus --&gt; RAM

    Note["🚨 BUS SATURATION&lt;br/&gt;120Hz 4K display consumes 40% BW&lt;br/&gt;NPU bandwidth slashed -&gt; Stutters"]:::bottleneck</code></pre>
<ul>
<li><p><strong>Interviewer:</strong> “Your AR app runs a real-time style transfer model. When the user upgrades to a Pro phone with a 120Hz ‘ProMotion’ display, the NPU inference suddenly starts stuttering and missing deadlines. Based on the UMA diagram, why is a faster screen slowing down your AI?”</p>
<details>
<summary>
<p><b>🔍 Reveal Answer</b></p>
</summary>
<p><strong>Common Mistake:</strong> “The phone is thermal throttling.” While heat is a factor, the immediate drop is due to memory bus physics.</p>
<p><strong>Realistic Solution:</strong> You are suffering from <strong>Memory Bus Contention</strong>. In a Unified Memory Architecture (UMA), the Display Controller, GPU, and NPU all share the same LPDDR5 bus. A 120Hz display must refresh the framebuffer twice as often as a 60Hz one, consuming a massive slice of the total bandwidth. The memory controller prioritizes the display to prevent tearing, starving the bandwidth-hungry NPU. The fix is to drop the refresh rate to 60Hz during heavy AR features or reduce NPU precision to INT8 to halve its bandwidth needs.</p>
<blockquote class="blockquote">
<p><strong>Napkin Math:</strong> A 4K 120Hz display requires moving ~4.5 GB/s just for frame refresh. On a phone with 50 GB/s peak bandwidth, the display system (plus GPU rendering) can easily consume 40-50% of the practical bus capacity.</p>
</blockquote>
<p>📖 <strong>Deep Dive:</strong> <a href="https://harvard-edge.github.io/cs249r_book_dev/contents/hw_acceleration/hw_acceleration.html">Hardware Acceleration</a></p>
</details></li>
</ul>



</section>


<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mlsysbook\.ai\/interviews\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../mobile/03_ship_and_update.html" class="pagination-link" aria-label="Ship &amp; Update">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Ship &amp; Update</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../tinyml/README.md" class="pagination-link" aria-label="🔬 TinyML Track">
        <span class="nav-page-text">🔬 TinyML Track</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2024-2026 Harvard University. Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC-BY-NC-SA 4.0</a></p>
</div>   
    <div class="nav-footer-center">
<p>Part of the <a href="https://mlsysbook.ai">Machine Learning Systems</a> textbook</p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/harvard-edge/cs249r_book">
      <i class="bi bi-github" role="img" aria-label="View source on GitHub">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>